### PR TITLE
added no_op_check flag to allow skipping op validation

### PR DESCRIPTION
**Pull request by pyu10055**
It is useful to allow skipping the op validation for converter, especially in node.js
env, where all op could be supported. 
It is also useful for development, converting models with not implmented ops.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/160)

### CODE REVIEW

**Comment by caisq** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[python/tensorflowjs/converters/tf_saved_model_conversion.py, line 77 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/160#-LFe2YiSDnKtNfW8W_sG:-LFe2YiT4-xnpl9fPlIM:b-cg0pfd) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/607d82ac38b9caf651b9212c0a3bb1ecc6d8255b/python/tensorflowjs/converters/tf_saved_model_conversion.py#L77)):*
> ```
>  no_op_check: Bool whether to perform the op check.
> ```

The negation her is confusing. Consider renaming the keyword argument to "skip_op_check".

---

*[python/tensorflowjs/converters/tf_saved_model_conversion_test.py, line 91 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/160#-LFe3QdtBuFKnAjTqmjO:-LFe3QdtBuFKnAjTqmjP:b-9tjll2) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/607d82ac38b9caf651b9212c0a3bb1ecc6d8255b/python/tensorflowjs/converters/tf_saved_model_conversion_test.py#L91)):*
> ```
> with graph.as_default():
> ```

Can you add a comment to mark which op is unsupported here?

---

*[python/tensorflowjs/converters/tf_saved_model_conversion_test.py, line 187 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/160#-LFe3Etk7WxvXD4nO5fB:-LFe3EtlC2H2fDnGNz7W:b-gn9czo) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/607d82ac38b9caf651b9212c0a3bb1ecc6d8255b/python/tensorflowjs/converters/tf_saved_model_conversion_test.py#L187)):*
> ```
>  # Load the saved weights as a JSON string.
> ```

nit: This is not weights per se, strictly speaking. It's the manifest of weights.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/160)*

**Comment by caisq** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[python/tensorflowjs/converters/converter.py, line 187 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/160#-LFe75Vg0S2wmtauqvFa:-LFe75Vh0ZJmAqU8Ho24:b1hd32r) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/607d82ac38b9caf651b9212c0a3bb1ecc6d8255b/python/tensorflowjs/converters/converter.py#L187)):*
> ```
> --no_op_check
> ```

How about calling it `--skip_op_check`. Negation increases cognitive load.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/160)*

**Comment by pyu10055** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[python/tensorflowjs/converters/converter.py, line 187 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/160#-LFe75Vg0S2wmtauqvFa:-LFehMC-EHVl_Ti4nl1J:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/607d82ac38b9caf651b9212c0a3bb1ecc6d8255b/python/tensorflowjs/converters/converter.py#L187)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> --no_op_check
> ```

How about calling it `--skip_op_check`. Negation increases cognitive load.
</blockquote></details>

Done.

---

*[python/tensorflowjs/converters/tf_saved_model_conversion.py, line 77 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/160#-LFe2YiSDnKtNfW8W_sG:-LFehPbU2fgMp8yc-nlM:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/607d82ac38b9caf651b9212c0a3bb1ecc6d8255b/python/tensorflowjs/converters/tf_saved_model_conversion.py#L77)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
>  no_op_check: Bool whether to perform the op check.
> ```

The negation her is confusing. Consider renaming the keyword argument to "skip_op_check".
</blockquote></details>

Done.

---

*[python/tensorflowjs/converters/tf_saved_model_conversion_test.py, line 91 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/160#-LFe3QdtBuFKnAjTqmjO:-LFehbP620CmRUR5ckZ7:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/607d82ac38b9caf651b9212c0a3bb1ecc6d8255b/python/tensorflowjs/converters/tf_saved_model_conversion_test.py#L91)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> with graph.as_default():
> ```

Can you add a comment to mark which op is unsupported here?
</blockquote></details>

Done.

---

*[python/tensorflowjs/converters/tf_saved_model_conversion_test.py, line 187 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/160#-LFe3Etk7WxvXD4nO5fB:-LFeho736UkoHbcvrzYB:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/607d82ac38b9caf651b9212c0a3bb1ecc6d8255b/python/tensorflowjs/converters/tf_saved_model_conversion_test.py#L187)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
>  # Load the saved weights as a JSON string.
> ```

nit: This is not weights per se, strictly speaking. It's the manifest of weights.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/160)*

**Comment by caisq** [comment]
:lgtm_strong:

---

Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[python/tensorflowjs/converters/tf_saved_model_conversion.py, line 182 at r2](https://reviewable.io/reviews/tensorflow/tfjs-converter/160#-LFp-7om1_cREfkx6Tfb:-LFp-7om1_cREfkx6Tfc:bh5gih0) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/71abd073cd79f13a98a1de1df4159f9df1bd06c3/python/tensorflowjs/converters/tf_saved_model_conversion.py#L182)):*
> ```
> perform
> ```

s/perform/skip/

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/160#-:-LFp-BLZ5Jqo7CEgL6VG:b-jbsf8z)*

**Pull request merged**
