### PR TITLE
Remove Arrow func

### PR DESCRIPTION
**Pull request by pyu10055**
manually fix the generated es6 compile_api.js file to be compatible with IE11, updated README with instructions.

fixed https://github.com/tensorflow/tfjs/issues/406

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/152)

### CODE REVIEW

**Comment by nsthorat** [comment]
Since this is so trivial, maybe you could automate this with a script? It seems unfortunate to instruct people to manually remove arrow functions.

Also, is there an es5 target you can use when generating the compiled_api.js?

**Comment by nsthorat** [comment]
Just remembered I made it es6, so disregard that.

**Comment by pyu10055** [comment]
good suggestion, added script to the conversion.

---

Review status: 0 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/152#-:-LEjyY50-o3tR3AzKMvn:bxve5fn)*

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/152#-:-LEzAAkc7Z3mn3K5Lyc2:b-jbsf8z)*

**Pull request merged**
