### PR TITLE
make sure the padding param is in the form of 2d array

### PR DESCRIPTION
**Pull request by pyu10055**
fix the issue tfjs issue #177

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/86)

### CODE REVIEW

**Comment by nsthorat** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[src/operations/executors/utils.ts, line 57 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/86#-LAKYwDj-NXW8GreGLCM:-LAKYwDj-NXW8GreGLCN:bhjpaah) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/467ea2ec6734fc613b5e087bab46ba301556aa3d/src/operations/executors/utils.ts#L57)):*
> ```XML
> }
> 
> export function reshape(arr: number[], size: number) {
> ```

I think this is more of a split op, right?

---

*[src/operations/executors/utils.ts, line 59 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/86#-LAKYoSSEu_ULZqq79EY:-LAKYoSX8_PbFPR0Ktam:b-7l1gdp) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/467ea2ec6734fc613b5e087bab46ba301556aa3d/src/operations/executors/utils.ts#L59)):*
> ```XML
> export function reshape(arr: number[], size: number) {
>   const res = [];
>   for (let i = 0; i < arr.length; i = i + size)
> ```

i += size

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/86)*

**Comment by pyu10055** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/operations/executors/utils.ts, line 57 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/86#-LAKYwDj-NXW8GreGLCM:-LAPIVQiAspXbIAC94F6:b-o08sds) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/467ea2ec6734fc613b5e087bab46ba301556aa3d/src/operations/executors/utils.ts#L57)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

I think this is more of a split op, right?
</blockquote></details>

it is not for op, but take the value of the tensor and reshape them for the op params.

---

*[src/operations/executors/utils.ts, line 59 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/86#-LAKYoSSEu_ULZqq79EY:-LAPJOAWD_hPaKQgyTV-:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/467ea2ec6734fc613b5e087bab46ba301556aa3d/src/operations/executors/utils.ts#L59)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

i += size
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/86)*

**Comment by nsthorat** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/operations/executors/utils.ts, line 57 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/86#-LAKYwDj-NXW8GreGLCM:-LAPSGyo3utlud2S3b5J:b-2qp0w7) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/467ea2ec6734fc613b5e087bab46ba301556aa3d/src/operations/executors/utils.ts#L57)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

it is not for op, but take the value of the tensor and reshape them for the op params.
</blockquote></details>

I guess I mean this isn't actually a reshape, but a split (since a reshape would take another shape and not size of the split). Maybe it should be called split.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/86)*

**Comment by pyu10055** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/operations/executors/utils.ts, line 57 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/86#-LAKYwDj-NXW8GreGLCM:-LAPg0lQC_m6vcF62Yoy:b-600na) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/467ea2ec6734fc613b5e087bab46ba301556aa3d/src/operations/executors/utils.ts#L57)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

I guess I mean this isn't actually a reshape, but a split (since a reshape would take another shape and not size of the split). Maybe it should be called split.
</blockquote></details>

got it, make sense.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/86)*

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/operations/executors/transformation_executor_test.ts, line 69 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/86#-LAPobIS7zKfyDF3Iayv:-LAPobIS7zKfyDF3Iayw:bjrbwb9) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/6f78349414d85e404c26b888c9bbc273b5664b02/src/operations/executors/transformation_executor_test.ts#L69)):*
> ```XML
>         node.params.constantValue = createNumberAttr(1);
>         node.inputNames = ['input1', 'input3'];
>         const input3 = [tfc.tensor2d([1, 1, 2, 2])];
> ```

Provide explicit shape in `tensor2d(flatArray, shape)`. This line should have thrown an error since shape is missing and the values are a flat array, but we had a bug. See https://github.com/tensorflow/tfjs-core/pull/969

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/86#-:-LAPoxmc-WLD3qPgjLKT:b-jbsf8z)*

**Comment by pyu10055** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[src/operations/executors/transformation_executor_test.ts, line 69 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/86#-LAPobIS7zKfyDF3Iayv:-LARISnE2T4Swhc1CJ2k:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/6f78349414d85e404c26b888c9bbc273b5664b02/src/operations/executors/transformation_executor_test.ts#L69)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

Provide explicit shape in `tensor2d(flatArray, shape)`. This line should have thrown an error since shape is missing and the values are a flat array, but we had a bug. See https://github.com/tensorflow/tfjs-core/pull/969
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/86)*

**Pull request merged**
