### PR TITLE
Add read_weights() and load_keras_model()

### PR DESCRIPTION
**Pull request by caisq**
This eanbles loading model topology and weight values stored
in TensorFlow.js-format binary files, potentially sharded.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/85)

### CODE REVIEW

**Comment by bileschi** [comment]
Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[python/tensorflowjs/read_weights_test.py, line 72 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LA-IFeA1_SemG0IXdER:-LA-IFeA1_SemG0IXdES:b-odmtaa) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/ed010ba0103e082eb013bbe93929b52528547f2c/python/tensorflowjs/read_weights_test.py#L72)):*
> ```
> 4 * 4
> ```
Why such a small shard_size_bytes?  Is this to exercise sharding?  If so, maybe highlight it with a comment?

---

*[python/tensorflowjs/converters/keras_tfjs_loader.py, line 81 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LA-Mmre6ZIIjt3bjAls:-LA-Mmre6ZIIjt3bjAlt:b-8ew6mz) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/ed010ba0103e082eb013bbe93929b52528547f2c/python/tensorflowjs/converters/keras_tfjs_loader.py#L81)):*
> ```
> -2
> ```
Can you add a comment about the cause of the -2 here?

---

*[python/tensorflowjs/converters/keras_tfjs_loader_test.py, line 16 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LA-p5TM1vA69VvzSC2j:-LA-p5TM1vA69VvzSC2k:bri2v6b) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/ed010ba0103e082eb013bbe93929b52528547f2c/python/tensorflowjs/converters/keras_tfjs_loader_test.py#L16)):*
> ```Python
> # ==============================================================================
> """Unite tests for keras_tfjs_loader."""
> ```

Impressive Testing!

---

*[python/tensorflowjs/converters/keras_tfjs_loader_test.py, line 103 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LA-na_U4i4_14lWBEms:-LA-na_U4i4_14lWBEmt:b-fhhnnd) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/ed010ba0103e082eb013bbe93929b52528547f2c/python/tensorflowjs/converters/keras_tfjs_loader_test.py#L103)):*
> ```
> testLoadKrasModelFromNonDefaultWeightsPathWorks
> ```
nit s/Kras/Keras/

---

*[python/tensorflowjs/converters/keras_tfjs_loader_test.py, line 129 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LA-oAaN8xy1kypvYhLh:-LA-oAaN8xy1kypvYhLi:b-9alfrp) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/ed010ba0103e082eb013bbe93929b52528547f2c/python/tensorflowjs/converters/keras_tfjs_loader_test.py#L129)):*
> ```
> scop
> ```
nit spelling.  Also, should the description read "enabling" instead of "disabling"?

---

*[python/tensorflowjs/converters/keras_tfjs_loader_test.py, line 142 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LA-oa6o-BczKEL78ldz:-LA-oa6o-BczKEL78le-:b47lln9) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/ed010ba0103e082eb013bbe93929b52528547f2c/python/tensorflowjs/converters/keras_tfjs_loader_test.py#L142)):*
> ```Python
>       for model1_weight_value, model2_weight_value in zip(
>           model1_weight_values, model2_weight_values):
>         self.assertAllClose(model1_weight_value, model2_weight_value)
> ```

Does it make sense to check that the names of model1 weights are suffixes of the names of model2 weights?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85)*

**Comment by bileschi** [comment]
:lgtm_strong:

---

Review status: 0 of 10 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-:-LA-p9U26krw1Mf44g98:b-jbsf8z)*

**Comment by caisq** [comment]
Review status: 0 of 11 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[python/tensorflowjs/read_weights_test.py, line 72 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LA-IFeA1_SemG0IXdER:-LA5Y1-V0zeSGNX20m23:b6e5orq) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/ed010ba0103e082eb013bbe93929b52528547f2c/python/tensorflowjs/read_weights_test.py#L72)):*
<details><summary><i>Previously, bileschi (Stanley Bileschi) wrote…</i></summary><blockquote>

> ```
> 4 * 4
> ```
Why such a small shard_size_bytes?  Is this to exercise sharding?  If so, maybe highlight it with a comment?
</blockquote></details>

The `shard_size_bytes` is actually unnecessary in this test, because we don't want sharding anyway. Removed (also in two other tests). Thanks.

---

*[python/tensorflowjs/converters/keras_tfjs_loader.py, line 81 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LA-Mmre6ZIIjt3bjAls:-LA5YvxX04gQVBBhkTTU:birdnsx) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/ed010ba0103e082eb013bbe93929b52528547f2c/python/tensorflowjs/converters/keras_tfjs_loader.py#L81)):*
<details><summary><i>Previously, bileschi (Stanley Bileschi) wrote…</i></summary><blockquote>

> ```
> -2
> ```
Can you add a comment about the cause of the -2 here?
</blockquote></details>

This is for removing the ":0" in weight names such as "dense1/kernel:0" from PyKeras running on TensorFlow backend. I'm now re-using an existing `normalize_weight_name()` method from the `keras_h5_conversion` module.

---

*[python/tensorflowjs/converters/keras_tfjs_loader_test.py, line 103 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LA-na_U4i4_14lWBEms:-LA5Zdz85ENF2k9g3osW:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/ed010ba0103e082eb013bbe93929b52528547f2c/python/tensorflowjs/converters/keras_tfjs_loader_test.py#L103)):*
<details><summary><i>Previously, bileschi (Stanley Bileschi) wrote…</i></summary><blockquote>

> ```
> testLoadKrasModelFromNonDefaultWeightsPathWorks
> ```
nit s/Kras/Keras/
</blockquote></details>

Done.

---

*[python/tensorflowjs/converters/keras_tfjs_loader_test.py, line 129 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LA-oAaN8xy1kypvYhLh:-LA5Znmu1PiKqfQhnVj8:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/ed010ba0103e082eb013bbe93929b52528547f2c/python/tensorflowjs/converters/keras_tfjs_loader_test.py#L129)):*
<details><summary><i>Previously, bileschi (Stanley Bileschi) wrote…</i></summary><blockquote>

> ```
> scop
> ```
nit spelling.  Also, should the description read "enabling" instead of "disabling"?
</blockquote></details>

Done.

---

*[python/tensorflowjs/converters/keras_tfjs_loader_test.py, line 142 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LA-oa6o-BczKEL78ldz:-LA5_b-23HT91F5vaJWn:b-4k0685) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/ed010ba0103e082eb013bbe93929b52528547f2c/python/tensorflowjs/converters/keras_tfjs_loader_test.py#L142)):*
<details><summary><i>Previously, bileschi (Stanley Bileschi) wrote…</i></summary><blockquote>

Does it make sense to check that the names of model1 weights are suffixes of the names of model2 weights?
</blockquote></details>

Good point! Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 11 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[python/tensorflowjs/read_weights.py, line 56 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LAIxs_SBQWO8OAQ15GM:-LAIxs_SBQWO8OAQ15GN:bcwz0b) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/7773fa70b3ba7952689d86d322a935736d041466/python/tensorflowjs/read_weights.py#L56)):*
> ```Python
>     for path in group['paths']:
>       with open(os.path.join(base_path, path), 'rb') as f:
>         buff += f.read()
> ```

consider a buffered writer for speed:
https://github.com/tensorflow/tfjs-converter/blob/master/python/tensorflowjs/write_weights.py#L128

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-:-LAIxzUm0zKCC40gJsZP:b-jbsf8z)*

**Comment by pyu10055** [comment]
:lgtm_strong:

---

Reviewed 1 of 10 files at r1.
Review status: 1 of 11 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[python/tensorflowjs/converters/keras_h5_conversion.py, line 49 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LAJV3ytDJURW4RzKV8X:-LAJV3ytDJURW4RzKV8Y:b-6uj9u7) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/7773fa70b3ba7952689d86d322a935736d041466/python/tensorflowjs/converters/keras_h5_conversion.py#L49)):*
> ```Python
>   if name.endswith(':0'):
>     # Python TensorFlow weight names ends with the output slot, which is
>     # not applicable to TensorFlow.js.
> ```

The output slot is relevant to tfjs, only the :0 is same as not having the output slot, which can be removed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-:-LAJW7KD3UycTQ3oajG0:b-jbsf8z)*

**Comment by caisq** [comment]
Review status: 1 of 11 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[python/tensorflowjs/read_weights.py, line 56 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LAIxs_SBQWO8OAQ15GM:-LAKT5254kqHqY5nisq5:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/71a4834434d8ffc337fd89b6087328ea347f6759/python/tensorflowjs/read_weights.py#L56)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

consider a buffered writer for speed:
https://github.com/tensorflow/tfjs-converter/blob/master/python/tensorflowjs/write_weights.py#L128
</blockquote></details>

Done.

---

*[python/tensorflowjs/converters/keras_h5_conversion.py, line 49 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LAJV3ytDJURW4RzKV8X:-LAKUawD8xzyp0WOt0GL:b-k7ytot) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/71a4834434d8ffc337fd89b6087328ea347f6759/python/tensorflowjs/converters/keras_h5_conversion.py#L49)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

The output slot is relevant to tfjs, only the :0 is same as not having the output slot, which can be removed.
</blockquote></details>

Right, this function is exactly doing that: discard the ":0" suffix, but not other suffices. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85)*

**Comment by dsmilkov** [comment]
:lgtm_strong: Nice work. Comments mostly about input validation - nothing major. Feel free to submit after

---

Reviewed 1 of 10 files at r1, 1 of 6 files at r2.
Review status: 3 of 11 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[python/setup.py, line 58 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LALRxjUDAE8vq2bMY2I:-LALRxjUDAE8vq2bMY2J:bgtjmm3) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8955c996d112022ac533be686da77180bacfebf7/python/setup.py#L58)):*
> ```Python
>         'tensorflowjs',
>         'tensorflowjs.version',
>         'tensorflowjs.read_weights',
> ```

can we expose these methods to the top-level namespace using a top-level `__init__.py` file? E.g. tensorflowjs.read_weights(....) instead of tensorflowjs.read_weights.read_weights().

---

*[python/tensorflowjs/read_weights.py, line 52 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LALRPys1CQIxQXn6X-z:-LALRPys1CQIxQXn6X0-:b-8m5xft) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8955c996d112022ac533be686da77180bacfebf7/python/tensorflowjs/read_weights.py#L52)):*
> ```Python
>     If `flatten` is `True`, returns a single weight group.
>   """
>   data_buffers = []
> ```

Might be good, here and elsewhere, to validate the format of the weights_manifest and error with user-friendly messages.

---

*[python/tensorflowjs/converters/keras_tfjs_loader.py, line 15 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LALPtPH4tT4PMjbAkF6:-LALPtPH4tT4PMjbAkF7:b-dfmymq) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8955c996d112022ac533be686da77180bacfebf7/python/tensorflowjs/converters/keras_tfjs_loader.py#L15)):*
> ```Python
> # limitations under the License.
> # ==============================================================================
> """Library for converting model and weights in TensorFlow.js format."""
> ```

How about: `Library for loading a Keras model from a TensorFlow.js format

---

*[python/tensorflowjs/converters/keras_tfjs_loader.py, line 44 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LALP7Gm0joXYDIfP92Z:-LALP7Gm0joXYDIfP92_:b33hslt) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8955c996d112022ac533be686da77180bacfebf7/python/tensorflowjs/converters/keras_tfjs_loader.py#L44)):*
> ```Python
>       If not specified (`None`), will assume the prefix is the same directory
>       as the dirname of `config_json_path`.
>     weights_data_buffers: A buffer os a `list` of buffers containing the weight
> ```

typo: s/os/or/. Also say: `Optional,` to be consistent with the previous argument

---

*[python/tensorflowjs/converters/keras_tfjs_loader.py, line 57 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LALTHof-e7N-sCzT77d:-LALTHof-e7N-sCzT77e:b-e2jfxq) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8955c996d112022ac533be686da77180bacfebf7/python/tensorflowjs/converters/keras_tfjs_loader.py#L57)):*
> ```Python
>     The loaded instance of `keras.Model`.
>   """
>   with open(config_json_path, 'rt') as f:
> ```

not sure how nice of an error message you get if config_json_path doesn't exist, but worth trying out and if you don't like it, doing your own check if the file exists.

---

*[python/tensorflowjs/converters/keras_tfjs_loader.py, line 60 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LALQGzb41DKy8Bo6pJm:-LALQGzb41DKy8Bo6pJn:bbigr2t) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8955c996d112022ac533be686da77180bacfebf7/python/tensorflowjs/converters/keras_tfjs_loader.py#L60)):*
> ```Python
>     model_and_weights_manifest = json.load(f)
> 
>   model_json = model_and_weights_manifest['modelTopology']
> ```

Some small validation of the format might be helpful at this point. E.g. error if modelTopology not found in the json with a user-friendly message about the format not being valid. 

---

*[python/tensorflowjs/converters/keras_tfjs_loader.py, line 66 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LALQfGeCGegLrqDGtwU:-LALQfGeCGegLrqDGtwV:b3yqxu5) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8955c996d112022ac533be686da77180bacfebf7/python/tensorflowjs/converters/keras_tfjs_loader.py#L66)):*
> ```Python
>   unique_name_scope = uuid.uuid4().hex if use_unique_name_scope else None
>   with tf.name_scope(unique_name_scope):
>     model = keras.models.model_from_json(json.dumps(model_json))
> ```

it's unfortunate that model_from_json takes only a string

---

*[python/tensorflowjs/converters/keras_tfjs_loader.py, line 69 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LALQu824L9IB1Qio09O:-LALQu824L9IB1Qio09P:b-ei1u9r) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8955c996d112022ac533be686da77180bacfebf7/python/tensorflowjs/converters/keras_tfjs_loader.py#L69)):*
> ```Python
> 
>   if load_weights:
>     weights_manifest = model_and_weights_manifest['weightsManifest']
> ```

do validation to make sure weightsManifest as a key is present and it's of a valid format.

---

*[python/tensorflowjs/converters/keras_tfjs_loader.py, line 74 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LALR5oQ3tr7MAloqOVb:-LALR5oQ3tr7MAloqOVc:b1rr63d) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8955c996d112022ac533be686da77180bacfebf7/python/tensorflowjs/converters/keras_tfjs_loader.py#L74)):*
> ```Python
>       if weights_path_prefix:
>         raise ValueError(
>             'The arguments weights_data_buffers and weights_path_prefix are '
> ```

might read easier (less mathy) if you say:
'Use either `weights_data_buffers` or `weights_path_prefix`, but not both'. Ditto for the docstring above

---

*[python/tensorflowjs/converters/keras_tfjs_loader_test.py, line 15 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LALPnks74EwrwE6e3kY:-LALPnks74EwrwE6e3kZ:b-d4mk8d) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8955c996d112022ac533be686da77180bacfebf7/python/tensorflowjs/converters/keras_tfjs_loader_test.py#L15)):*
> ```Python
> # limitations under the License.
> # ==============================================================================
> """Unite tests for keras_tfjs_loader."""
> ```

s/unite/unit

---

*[python/tensorflowjs/converters/keras_tfjs_loader_test.py, line 200 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LALUKTk4KKzez_y2Gqi:-LALUKTk4KKzez_y2Gqj:blpjal5) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8955c996d112022ac533be686da77180bacfebf7/python/tensorflowjs/converters/keras_tfjs_loader_test.py#L200)):*
> ```Python
>             weights_data_buffers=[b'foo'], weights_path_prefix='bar')
> ```

Might be good to add a test where the json format is invalid

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-:-LALUeBM3zWNzmM_zEAq:bko4dfl)*

**Comment by caisq** [comment]
Review status: 3 of 11 files reviewed at latest revision, 19 unresolved discussions, all commit checks successful.

---

*[python/setup.py, line 58 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LALRxjUDAE8vq2bMY2I:-LAOooE_0NyM8IVqMhht:b5n3pl2) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8955c996d112022ac533be686da77180bacfebf7/python/setup.py#L58)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

can we expose these methods to the top-level namespace using a top-level `__init__.py` file? E.g. tensorflowjs.read_weights(....) instead of tensorflowjs.read_weights.read_weights().
</blockquote></details>

My hunch is: let's do this on users' demand. If we or some users find it useful to have those as public methods in the future, we can consider adding them. Otherwise, let's keep them as not public, as it gives us more flexibility in changing implementation in the future.

---

*[python/tensorflowjs/read_weights.py, line 52 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LALRPys1CQIxQXn6X-z:-LAOtDX9CBSbBwtc8Dc3:bz2feeo) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8955c996d112022ac533be686da77180bacfebf7/python/tensorflowjs/read_weights.py#L52)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

Might be good, here and elsewhere, to validate the format of the weights_manifest and error with user-friendly messages.
</blockquote></details>

Added a little validation with unit tests.

---

*[python/tensorflowjs/converters/keras_tfjs_loader.py, line 15 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LALPtPH4tT4PMjbAkF6:-LAOviJrDE_kZpxBJ2Pz:b-kvqbth) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8955c996d112022ac533be686da77180bacfebf7/python/tensorflowjs/converters/keras_tfjs_loader.py#L15)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

How about: `Library for loading a Keras model from a TensorFlow.js format
</blockquote></details>

Done with minor modification. Thanks.

---

*[python/tensorflowjs/converters/keras_tfjs_loader.py, line 44 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LALP7Gm0joXYDIfP92Z:-LAOvoEk-uTsiid1YxdA:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8955c996d112022ac533be686da77180bacfebf7/python/tensorflowjs/converters/keras_tfjs_loader.py#L44)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

typo: s/os/or/. Also say: `Optional,` to be consistent with the previous argument
</blockquote></details>

Done.

---

*[python/tensorflowjs/converters/keras_tfjs_loader.py, line 57 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LALTHof-e7N-sCzT77d:-LAOw2ynEGSEhqoftML6:b-exikdp) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8955c996d112022ac533be686da77180bacfebf7/python/tensorflowjs/converters/keras_tfjs_loader.py#L57)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

not sure how nice of an error message you get if config_json_path doesn't exist, but worth trying out and if you don't like it, doing your own check if the file exists.
</blockquote></details>

It looks like:
IOError: [Errno 2] No such file or directory: '/tmp/asdfa'

which looks fine to me.

---

*[python/tensorflowjs/converters/keras_tfjs_loader.py, line 66 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LALQfGeCGegLrqDGtwU:-LAOy0RP6nWmbdnM-HK1:bkx729a) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8955c996d112022ac533be686da77180bacfebf7/python/tensorflowjs/converters/keras_tfjs_loader.py#L66)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

it's unfortunate that model_from_json takes only a string
</blockquote></details>

Added some validation.

---

*[python/tensorflowjs/converters/keras_tfjs_loader.py, line 69 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LALQu824L9IB1Qio09O:-LAOy8KD2hVajgYJFxT3:bkx729a) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8955c996d112022ac533be686da77180bacfebf7/python/tensorflowjs/converters/keras_tfjs_loader.py#L69)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

do validation to make sure weightsManifest as a key is present and it's of a valid format.
</blockquote></details>

Added some validation.

---

*[python/tensorflowjs/converters/keras_tfjs_loader_test.py, line 15 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LALPnks74EwrwE6e3kY:-LAOyXHTE1kQqeK_X7io:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8955c996d112022ac533be686da77180bacfebf7/python/tensorflowjs/converters/keras_tfjs_loader_test.py#L15)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

s/unite/unit
</blockquote></details>

Done.

---

*[python/tensorflowjs/converters/keras_tfjs_loader_test.py, line 200 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85#-LALUKTk4KKzez_y2Gqi:-LAP-44bCZl-hMXvMMTz:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8955c996d112022ac533be686da77180bacfebf7/python/tensorflowjs/converters/keras_tfjs_loader_test.py#L200)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

Might be good to add a test where the json format is invalid
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/85)*

**Pull request merged**
