### PR TITLE
Execute error

### PR DESCRIPTION
**Pull request by pyu10055**
added detail message if the input is missing necessary placeholders

expose both the input and output node names for the model graph

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/83)

### CODE REVIEW

**Comment by nsthorat** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[src/executor/graph_executor.ts, line 110 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/83#-L9gaifU5BXz3Z9GV3h_:-L9gaifU5BXz3Z9GV3ha:b-gvqq8) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/f051cc09fceb48620ecfa32c6d0a3380f51804b2/src/executor/graph_executor.ts#L110)):*
> ```XML
>   }
> 
>   private checkInput(inputs: NamedTensorsMap) {
> ```

it would also be good to throw an error if you provide an input that doesn't exist as a placeholder

---

*[src/executor/graph_executor.ts, line 114 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/83#-L9gafwYDn24vR_OZs02:-L9gafwYDn24vR_OZs03:b-jjzns0) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/f051cc09fceb48620ecfa32c6d0a3380f51804b2/src/executor/graph_executor.ts#L114)):*
> ```XML
>     const missing: string[] = [];
>     this.placeholders.forEach(name => {
>       if (inputKeys.indexOf(name) === -1) missing.push(name);
> ```

use {}

---

*[src/operations/operation_mapper.ts, line 36 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/83#-L9gatwm4xt7WFQhFzdt:-L9gatwm4xt7WFQhFzdu:bswsnwc) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/f051cc09fceb48620ecfa32c6d0a3380f51804b2/src/operations/operation_mapper.ts#L36)):*
> ```XML
> 
> const CONTROL_FLOW_OPS =
>     ['Switch', 'Merge', 'Enter', 'Exit', 'NextIteration', 'LoopCond'];
> ```

is this meant to be in this PR?

---

*[src/operations/operation_mapper.ts, line 78 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/83#-L9gapIOApbUddzg5HJq:-L9gapIOApbUddzg5HJr:b-jjzns0) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/f051cc09fceb48620ecfa32c6d0a3380f51804b2/src/operations/operation_mapper.ts#L78)):*
> ```XML
>       map[node.name] = this.mapNode(node);
>       if (this.isControlFlow(node)) withControlFlow = true;
>       if (node.op === 'Placeholder') placeholders.push(map[node.name]);
> ```

use {}

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/83)*

**Comment by pyu10055** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/executor/graph_executor.ts, line 110 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/83#-L9gaifU5BXz3Z9GV3h_:-L9ge-FiDmNPmH5OjLOq:beptjq6) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/f051cc09fceb48620ecfa32c6d0a3380f51804b2/src/executor/graph_executor.ts#L110)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

it would also be good to throw an error if you provide an input that doesn't exist as a placeholder
</blockquote></details>

good call, added.

---

*[src/executor/graph_executor.ts, line 114 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/83#-L9gafwYDn24vR_OZs02:-L9ge1B18NoI_jIuSvIe:boglh57) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/f051cc09fceb48620ecfa32c6d0a3380f51804b2/src/executor/graph_executor.ts#L114)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

use {}
</blockquote></details>

the ts style guide allow single line to omit the braces. 
https://g3doc.corp.google.com/javascript/typescript/g3doc/styleguide.md?cl=head#control-flow-statements-blocks
let me know if you think otherwise.

---

*[src/operations/operation_mapper.ts, line 36 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/83#-L9gatwm4xt7WFQhFzdt:-L9geFac6cnEG7K0t73l:b-lot39o) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/f051cc09fceb48620ecfa32c6d0a3380f51804b2/src/operations/operation_mapper.ts#L36)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

is this meant to be in this PR?
</blockquote></details>

not for this cl, I will revert the change.

---

*[src/operations/operation_mapper.ts, line 78 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/83#-L9gapIOApbUddzg5HJq:-L9geR4kEjdBLZKd86Pr:b-r26qah) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/f051cc09fceb48620ecfa32c6d0a3380f51804b2/src/operations/operation_mapper.ts#L78)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

use {}
</blockquote></details>

same as earlier.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/83)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/83#-:-L9h4yC3EKnJfdRZ2HEF:b-jbsf8z)*

**Comment by 24rochak** [comment]
I am trying to convert the frozen inference graph of [DeepLab](http://download.tensorflow.org/models/deeplabv3_mnv2_pascal_train_aug_2018_01_29.tar.gz) hosted at their [model zoo](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md). 

The conversion was successful but when I load the model I get the following output : 

`Error importing the graph: block_shape must be positive for 'MobilenetV2/expanded_conv_7/depthwise/depthwise/SpaceToBatchND' (op: 'SpaceToBatchND') with input shapes: [1,?,?,384], [2], [2,2] and with computed input tensors: input[1] = <0 0>, input[2] = <[0 0][0 0]>.
Process finished with exit code 2`

The script which I use for loading the converted is : 

    graph_def = None
    graph = None
    model_file = "tensorflowjs_model.pb"
    
    print('Loading graph definition ...', file=sys.stderr)
    try:
        with tf.gfile.GFile(model_file, "rb") as f:
            graph_def = tf.GraphDef()
            graph_def.ParseFromString(f.read())
    except BaseException as e:
        parser.exit(2, 'Error loading the graph definition: {}'.format(str(e)))
    
    print('Importing graph ...', file=sys.stderr)
    try:
        assert graph_def is not None
        with tf.Graph().as_default() as graph:  # type: tf.Graph
            tf.import_graph_def(
                graph_def,
                name=''
            )
    except BaseException as e:
    parser.exit(2, 'Error importing the graph: {}'.format(str(e)))

**Pull request merged**
