### PR TITLE
[0.8.x]: Bump numpy version

### PR DESCRIPTION
**Pull request by sdll**
Resolves https://github.com/tensorflow/tfjs/issues/1600.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/368)

### CODE REVIEW

**Comment by dsmilkov** [comment]
Hi, sometimes cloud fails to start. To re-kick the CI, can you push an empty commit with `git commit -m 'empty' --allow-empty && git push`. Thanks!

**Comment by sdll** [comment]
@dsmilkov, I have triggered the CI as you recommended.

@pyu10055, the relevant changes are in https://github.com/tensorflow/tfjs-converter/pull/369.

**Comment by pyu10055** [comment]
> @dsmilkov, I have triggered the CI as you recommended.
> 
> @pyu10055, the relevant changes are in #369.

@sdll can you try to trigger the CI build again? No sure why it is still failing.

**Comment by sdll** [comment]
@pyu10055, done. The point is to trigger Travis, right?

**Comment by dsmilkov** [comment]
The only theory I have is that Cloud Build gets confused when the branch has slash in the name (in this case `legacy/bump-numpy-version`). @sdll can you open a new PR from a branch that doesn't have a slash in the name? Thank you!

**Pull request closed without merging**
