### PR TITLE
support for image resizeBilinear op

### PR DESCRIPTION
**Pull request by pyu10055**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/82)

### CODE REVIEW

**Comment by nsthorat** [comment]
:lgtm_strong:

Nice work Ping, this looks good. 

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/operations/executors/image_executor_test.ts, line 40 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/82#-L9gZnv29NRCjgO0JIxv:-L9gZnv29NRCjgO0JIxw:b-s2c2sg) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/74e838f9692199726f747305e8407bbec92497ec/src/operations/executors/image_executor_test.ts#L40)):*
> ```XML
> 
>   describe('executeOp', () => {
>     describe('resizeBilinear', () => {
> ```

is this nested describe intentional? i didnt know this was possible, you might want to flatten :)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/82#-:-L9gZhdFCoA7nFoumkix:b9gujvi)*

**Comment by nsthorat** [comment]
Looks like build is failing, make sure you fix that before merging

**Comment by pyu10055** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/operations/executors/image_executor_test.ts, line 40 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/82#-L9gZnv29NRCjgO0JIxv:-L9garVv85i9P5sqaKrM:b-7lofr3) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/74e838f9692199726f747305e8407bbec92497ec/src/operations/executors/image_executor_test.ts#L40)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

is this nested describe intentional? i didnt know this was possible, you might want to flatten :)
</blockquote></details>

yes, the nested describe is intentional, to give better description of the tests.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/82)*

**Comment by maltebaumann** [comment]
Hi and thank you for the great work! I converted a `SavedModel` with `ResizeBilinear` using the v0.1.2 pip package released a few hours ago, but if I try to load said model using the `@tensorflow/tfjs-converter` package, I see "TensorFlow Op is not supported: ResizeBilinear".

I might be mistaken, but to me it looks like the new image ops are not registered in the `OperationMapper`. I can manually add the `./op_list/image.json` file and the error disappears.

**Comment by maltebaumann** [comment]
Hey @dsmilkov I'm running 0.1.2 of the `tjfs-converter` package as well. Even in the current master branch, the `image.json` ops aren't included in the `OperationMapper`. Just take a look at [tfjs-converter/src/operations/operation_mapper.ts](https://github.com/tensorflow/tfjs-converter/blob/master/src/operations/operation_mapper.ts).

**Comment by dsmilkov** [comment]
@pyu10055 Can you take a look? Thanks!

**Pull request merged**
