### PR TITLE
Use node url api

### PR DESCRIPTION
**Pull request by ericmorgan1**
Hello,

React Native does not currently support `URL` objects.
See constructor: [https://github.com/facebook/react-native/blob/master/Libraries/Blob/URL.js](https://github.com/facebook/react-native/blob/master/Libraries/Blob/URL.js)

`frozen_model.ts` uses `URL` to parse a URL when loading a model.
This is one of a few issues in getting `tfjs-converter` to be compatible with React Native.

There is already some fallback code, so we can utilize that if `URL` is not supported.

Please let me know if you agree with this PR or if you think there is potentially a better way to support this.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/114)

### CODE REVIEW

**Comment by pyu10055** [comment]
thank you for looking into this issue. Even we detect that URL is not supported,
Overall, we should move away from browser URL approach, we should use node.js url npm instead (https://www.npmjs.com/package/url), so we can be sure the url is supported on all platform (browser, node, reactive native).

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/executor/frozen_model.ts, line 50 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/114#-LC1RQ-bCLUOJBGDgE-c:-LC1RQ-bCLUOJBGDgE-d:bygu2gf) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/4539d412fefde9f1d70f0cb90a8662ad576adcc4/src/executor/frozen_model.ts#L50)):*
> ```XML
>   private getPathPrefix() {
>     const isAbsolute = /^[a-z][a-z0-9+.-]*:/.test(this.weightManifestUrl);
>     var isURLSupported = true;
> ```

in typescript use let instead of var.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/114#-:-LC1RWLdCkPrBxaas543:b-v37pi1)*

**Comment by ericmorgan1** [comment]
@pyu10055 
Thanks for the comments. If it is ok to add the npm url dependency, I can look into switching to that.

**Comment by ericmorgan1** [comment]
Hi,

Please take a look at the update.

One difference between this `Url` and the browser `URL` is that the browser `URL` will add the '/' to `pathname`.
This api will not do that, so I concatenated a '/' at the end.

**Comment by pyu10055** [comment]
:lgtm_strong: with one minor suggestion, thanks!

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/executor/frozen_model_test.ts, line 86 at r3](https://reviewable.io/reviews/tensorflow/tfjs-converter/114#-LC4yvYQ1Lh0HN-Necr9:-LC4yvYQ1Lh0HN-NecrA:b6yhzoh) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/37b8518893f52c0d83f8b22c1ed8f9454eb32564/src/executor/frozen_model_test.ts#L86)):*
> ```XML
>   describe('getPathPrefix', () => {
>     it('should set pathPrefix', async () => {
>       model = new FrozenModel(MODEL_URL, WEIGHT_MANIFEST_URL);
> ```

can you add a test for relative weight manifest url? thanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/114#-:-LC4zT1R0ZMpEMfGyMR4:b-bv6k7g)*

**Comment by ericmorgan1** [comment]
FYI:
Previous code would return `'/path'`
New code will return `'/path/'`

Either way is handled, though:
https://github.com/tensorflow/tfjs-core/blob/536de43f134c4b0d56f4d727d061474b79e289d3/src/io/weights_loader.ts#L118

**Pull request merged**
