### PR TITLE
Bump version to 0.5.0

### PR DESCRIPTION
**Pull request by caisq**
tfjs-core dependency: 0.11.9 --> 0.12.0

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/165)

### CODE REVIEW

**Comment by caisq** [comment]
@pyu10055 Did TensorInfo get removed in tfjs-core 0.12.0? https://travis-ci.org/tensorflow/tfjs-converter/jobs/399303572

**Comment by nsthorat** [comment]
This should fix the issue: https://github.com/tensorflow/tfjs-converter/pull/166

**Comment by caisq** [comment]
PTAL again, @nsthorat?

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/165#-:-LGVcY345sXFtsWSV7qO:b-jbsf8z)*

**Pull request merged**
