### PR TITLE
use tf 2.0 pip instead of nightly build

### PR DESCRIPTION
**Pull request by pyu10055**
This is a more stable pip build for TF 2.0 instead of the nightly.
It will be updated roughly every two weeks and maintained after alpha too.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/354)

### CODE REVIEW

**Comment by dsmilkov** [comment]
If I understand correctly, because python lacks lock files (like `yarn.lock`), it will attempt to download the latest nightly which might have bugs and break our CI builds, while this gives us some stability within 2 weeks. But Ping, please correct me if your motivation was different.

**Comment by pyu10055** [comment]
> If I understand correctly, because python lacks lock files (like `yarn.lock`), it will attempt to download the latest nightly which might have bugs and break our CI builds, while this gives us some stability within 2 weeks. But Ping, please correct me if your motivation was different.

Yes, as Daniel described, tensorflow pip is a less frequently updated repo, which also means only the stable releases from 2.0 nightly will be pushed to it.

**Comment by caisq** [comment]
@pyu10055 Yes, it's less frequently updated. In fact it hasn't been updated since early March. There have been some bug fixes (e.g., the keras JSON issue) since then, by doing this, we are going to bring the bug back.

**Comment by dsmilkov** [comment]
We don't want to bring any bugs back :) I think the correct way is then to change our unit tests to not test internal details of TF C/Python. For example, we shouldn't test the exact graph node names.

Also, let's change our READMEs to encourage people to use this tool in a virtual env or docker container. Perhaps, we can even detect if we are in a virtual env and warn the user before the scripts proceeds

**Pull request merged**
