### PR TITLE
Bump version to 0.3.1

### PR DESCRIPTION
**Pull request by caisq**
Increase tfjs-core dependency version to 0.10.0

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/117)

### CODE REVIEW

**Comment by bileschi** [comment]
:lgtm_strong:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/117#-:-LC5JXCeCzN12K4f1Sw4:b-jbsf8z)*

**Comment by davidsoergel** [comment]
:lgtm_strong:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/117#-:-LC5JckA2APdlMvtPPkM:b-jbsf8z)*

**Comment by caisq** [comment]
cc @vbardiovskyg

**Comment by pyu10055** [comment]
:lgtm_strong: can you update the demo package.json as well, thanks!

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/117#-:-LC5TZ7k3SUZkFM24pP0:bm9r9a5)*

**Comment by caisq** [comment]
@pyu10055 I'll update the demo package.json in a separate PR.

**Pull request merged**
