### PR TITLE
Move dev dependencies to separate requirements file

### PR DESCRIPTION
**Pull request by ManrajGrover**
This PR moves dependencies required for development to separate file. Also, simplifies travis execution a little.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/80)

### CODE REVIEW

**Comment by ManrajGrover** [comment]
@caisq I didn't check `setup.py`. Apologies for that.

I feel that if we need to add a dependency, we would need to make changes in both `requirements.txt` and `setup.py`. We can add a dependency to `requirements.txt` and read the file content into a list in `setup.py` which would reduce the hassle.

**Comment by caisq** [comment]
@ManrajGrover No worries. Thank for your effort to make this into a cleaner shape.

Tying requirements.txt in with setup.py sounds good to me and I like the idea of reducing duplication, although I'm not sure how to do that in a not-too-contorted way. If you have ideas, feel free to push them up for review.

**Comment by ManrajGrover** [comment]
@caisq I've pushed some changes that might solve this. Please review and let me know if it works.

**Comment by caisq** [comment]
:lgtm_strong:

Thanks, Manraj!

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[python/setup.py, line 20 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/80#-L9vkxyR0RVdyhBnjO-Q:-L9vkxyR0RVdyhBnjO-R:b224foc) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/4b932a3d0343124114b63a9ccf2be18704b2658b/python/setup.py#L20)):*
> ```
> get_requirements
> ```

nit: since this method is not intended to be used by anything other than this file make it private, i.e., `def _get_requirements`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/80#-:-L9vlIuABecfzWKtQEeN:b-lazeru)*

**Comment by caisq** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[python/setup.py, line 66 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/80#-L9vlYZg99nWwxL8KCnD:-L9vlYZg99nWwxL8KCnE:bsvygj5) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/4b932a3d0343124114b63a9ccf2be18704b2658b/python/setup.py#L66)):*
> ```
> get_requirements
> ```

You probably want to do something like

`os.path.join(os.path.dirname(__file__), 'requirements.txt')`

so this file can be invoked from any directory, not just its own directory.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/80)*

**Comment by caisq** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[python/setup.py, line 21 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/80#-LA-ZAyDA4GhUDd_UbjX:-LA-ZAyDA4GhUDd_UbjY:beok0f2) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/022a89b45091ade7e74d16b77ab1908a38366d41/python/setup.py#L21)):*
> ```
> DIR_NAME
> ```

Where is `DIR_NAME` used?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/80)*

**Comment by ManrajGrover** [comment]
@caisq Ready for review. I had made the change but forgot to commit and push. Apologies for that.

**Comment by caisq** [comment]
LGTM. Merge after all tests pass :)

**Pull request merged**
