### PR TITLE
Use rollup.

### PR DESCRIPTION
**Pull request by nsthorat**
This change does the following:
- Convert to rollup for bundling. Remove browserify.
- Use "extend: true" to extend a global "tf" object. There is now no "tf_converter".
- Ship es6 in a dist-es6 folder as well as es5.
- Remove all index.ts files. They are not needed and just introduce another layer of indirection.

Converter here (rollup for all other packages has been released):
https://storage.googleapis.com/dljs-test/rollup/tf-converter.js

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/136)

### CODE REVIEW

**Comment by pyu10055** [comment]
At the bottom of the README file. https://github.com/tensorflow/tfjs-converter/blob/master/README.md, 
instead of generate for commonjs
node_modules/protobufjs/bin/pbjs -t static-module -w commonjs -o src/data/compiled_api.js --no-create --no-encode --no-verify --no-convert --no-delimited --no-beautify src/data/api.proto

replace with es6
node_modules/protobufjs/bin/pbjs -t static-module -w es6 -o src/data/compiled_api.js --no-create --no-encode --no-verify --no-convert --no-delimited --no-beautify src/data/api.proto

Is the clean up of the index.ts required for rollup, can that change be delayed to a separate PR to reduce the complexity?

---

Review status: 0 of 50 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/executor/graph_executor.ts, line 21 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/136#-LCoaNLH7EDVocc_Qen0:-LCoaNLH7EDVocc_Qen1:bwpdmpi) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/52ab63bbb822473d37e2f1a857b834bfa01f22b5/src/executor/graph_executor.ts#L21)):*
> ```
> operations
> ```
This is the wrong import, it should be operations.executeOp. It happened on other locations as well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/136#-:-LCoavPg8LTFKQnqZshy:b74m1lc)*

**Comment by nsthorat** [comment]
Rollup was having issues with the multiple layers of exports, especially through the commonjs module.

Got the build working now.

When I run "yarn test" locally, only 1 test runs -- is this a bug?

---

Review status: 0 of 55 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/executor/graph_executor.ts, line 21 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/136#-LCoaNLH7EDVocc_Qen0:-LCyVFGV6lS0JguHnzUF:bl2o2rf) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/52ab63bbb822473d37e2f1a857b834bfa01f22b5/src/executor/graph_executor.ts#L21)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

> ```
> operations
> ```
This is the wrong import, it should be operations.executeOp. It happened on other locations as well.
</blockquote></details>

Hmm.. not sure how this is wrong. I removed the index, so I'm importing executeOp directly from operation_executor.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/136#-:-LCoeMEN4svnSS6WIHni:bc3qdyw)*

**Comment by nsthorat** [comment]
I signed it!

**Comment by nsthorat** [comment]
This is ready for review now!

**Comment by pyu10055** [comment]
thanks for fixing this!

---

Review status: 0 of 55 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[rollup.config.js, line 28 at r2](https://reviewable.io/reviews/tensorflow/tfjs-converter/136#-LD-gjI83mguBVPelZ-Z:-LD-gjI83mguBVPelZ-_:b-4hksfo) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/4881866ec7572424d410a16a399be42c8f520fe9/rollup.config.js#L28)):*
> ```
> json
> ```

remove?

---

*[demo/package.json, line 9 at r2](https://reviewable.io/reviews/tensorflow/tfjs-converter/136#-LD-h4215wtwJMLwNI9R:-LD-h4215wtwJMLwNI9S:b5ydrza) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/4881866ec7572424d410a16a399be42c8f520fe9/demo/package.json#L9)):*
> ```
> tensorflow
> ```
change local file dependency to npm version, maybe also update core to 0.11.0

---

*[scripts/build.sh, line 26 at r2](https://reviewable.io/reviews/tensorflow/tfjs-converter/136#-LD-hnj07LTAw5U4qruN:-LD-hnj07LTAw5U4qruO:b-owf0g1) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/4881866ec7572424d410a16a399be42c8f520fe9/scripts/build.sh#L26)):*
> ```
> compiled_api
> ```
for es6 it should copy the compiled_api.js in the data/es6 directory, it also need compiled_api.d.ts

I add this change in the package.json build script section, maybe it should be calling this to reduce the duplication.

---

*[src/executor/frozen_model.ts, line 21 at r2](https://reviewable.io/reviews/tensorflow/tfjs-converter/136#-LD-iRV26zpMZ6DBcb_u:-LD-iRV26zpMZ6DBcb_v:b-l8x53t) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/4881866ec7572424d410a16a399be42c8f520fe9/src/executor/frozen_model.ts#L21)):*
> ```
> proto
> ```
should this be reverted back to import tensorflow directly from compiled_api?

---

*[src/executor/graph_executor.ts, line 21 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/136#-LCoaNLH7EDVocc_Qen0:-LD-igr_6KeTUljRatEG:b-uex7eb) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/52ab63bbb822473d37e2f1a857b834bfa01f22b5/src/executor/graph_executor.ts#L21)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

Hmm.. not sure how this is wrong. I removed the index, so I'm importing executeOp directly from operation_executor.
</blockquote></details>

It was importing from creation_executor, I changed it in one of my submit.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/136#-:-LD-jYznBQl2monpZ9s_:b-d0pxd3)*

**Comment by pyu10055** [comment]
:lgtm_strong:

---

Review status: 0 of 55 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/136#-:-LD-jjda4pYv6c4G4Bv2:b-jbsf8z)*

**Comment by pyu10055** [comment]
couple minor comments, please fix those before merge. Thanks.

---

Review status: 0 of 55 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/136#-:-LD-jnNM94jjeJ7wi2CC:b-m9u1m2)*

**Comment by nsthorat** [comment]
Review status: 0 of 55 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[rollup.config.js, line 28 at r2](https://reviewable.io/reviews/tensorflow/tfjs-converter/136#-LD-gjI83mguBVPelZ-Z:-LD1hb8B9Gsfj_xdQ-YW:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/4881866ec7572424d410a16a399be42c8f520fe9/rollup.config.js#L28)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

> ```
> json
> ```

remove?
</blockquote></details>

Done.

---

*[demo/package.json, line 9 at r2](https://reviewable.io/reviews/tensorflow/tfjs-converter/136#-LD-h4215wtwJMLwNI9R:-LD1i1nOCahPVCciOQ6V:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/4881866ec7572424d410a16a399be42c8f520fe9/demo/package.json#L9)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

> ```
> tensorflow
> ```
change local file dependency to npm version, maybe also update core to 0.11.0
</blockquote></details>

Done.

---

*[scripts/build.sh, line 26 at r2](https://reviewable.io/reviews/tensorflow/tfjs-converter/136#-LD-hnj07LTAw5U4qruN:-LD1i7-O37NpilEbCMSZ:b-h06cmf) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/4881866ec7572424d410a16a399be42c8f520fe9/scripts/build.sh#L26)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

> ```
> compiled_api
> ```
for es6 it should copy the compiled_api.js in the data/es6 directory, it also need compiled_api.d.ts

I add this change in the package.json build script section, maybe it should be calling this to reduce the duplication.
</blockquote></details>

Deleted this file since you added it to package.json.

---

*[src/executor/frozen_model.ts, line 21 at r2](https://reviewable.io/reviews/tensorflow/tfjs-converter/136#-LD-iRV26zpMZ6DBcb_u:-LD1iDkH5dU_grCq6JHU:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/4881866ec7572424d410a16a399be42c8f520fe9/src/executor/frozen_model.ts#L21)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

> ```
> proto
> ```
should this be reverted back to import tensorflow directly from compiled_api?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/136)*

**Pull request merged**
