### PR TITLE
Implementation of Snapshot Op

### PR DESCRIPTION
**Pull request by jsawruk**
Add support for the [Snapshot op](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/snapshot) in converted models.

The snapshot op returns a copy of the given tensor.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/111)

### CODE REVIEW

**Comment by pyu10055** [comment]
Thank you for the contribution, your code format is bit off, can you follow
https://github.com/tensorflow/tfjs-converter#development

to install the plugin for vs code and update the format? Thanks!

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/111#-:-LC-X7MI-qNUsEr1regF:bgdd1bn)*

**Comment by jsawruk** [comment]
The formatting should now be fixed.

**Comment by pyu10055** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/operations/op_mapper_schema.json, line 124 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/111#-LC4Fhrs6mNH_7uKaoZx:-LC4Fhrs6mNH_7uKaoZy:bx4ahtz) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/889314f02dc4acc8595c6f3160293af3b78a069b/src/operations/op_mapper_schema.json#L124)):*
> ```JSON
>     "type": "array"
> }
> ```

can you revert the change on this file?

---

*[src/operations/executors/graph_executor_test.ts, line 76 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/111#-LC4Flc33LgoS_jerbqF:-LC4Flc33LgoS_jerbqG:b-w0eoe4) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/814c25afa6a7db7d039de94898e3f949faaa5b39/src/operations/executors/graph_executor_test.ts#L76)):*
> ```XML
>         node.params.x = createTensorAttr(0);
>         node.op = 'snapshot';
>         expect(executeOp(node, {input: input1}, context)).toEqual(input1);
> ```

since the tensor is clone, it won't be the same as the original one, you should check the rank and value of the tensor instead.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/111)*

**Comment by pyu10055** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/operations/executors/graph_executor_test.ts, line 76 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/111#-LC4Flc33LgoS_jerbqF:-LC9uLoSBFOVsnnIRJDp:b-caqien) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/814c25afa6a7db7d039de94898e3f949faaa5b39/src/operations/executors/graph_executor_test.ts#L76)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

since the tensor is clone, it won't be the same as the original one, you should check the rank and value of the tensor instead.
</blockquote></details>

you can use expectArraysClose to check the value of the tensors.

import { expectArraysClose } from '@tensorflow/tfjs-core/dist/test_util';

expectArraysClose(result, [1]);

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/111)*

**Comment by nsthorat** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/operations/executors/graph_executor_test.ts, line 76 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/111#-LC4Flc33LgoS_jerbqF:-LCA11auD98hMthZwBMo:bcg0s8s) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/814c25afa6a7db7d039de94898e3f949faaa5b39/src/operations/executors/graph_executor_test.ts#L76)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

you can use expectArraysClose to check the value of the tensors.

import { expectArraysClose } from '@tensorflow/tfjs-core/dist/test_util';

expectArraysClose(result, [1]);
</blockquote></details>

Don't import using dist since this file may move. Use the public facing API by importing test_util from the public package.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/111)*

**Comment by pyu10055** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/operations/executors/graph_executor_test.ts, line 76 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/111#-LC4Flc33LgoS_jerbqF:-LCAh8y2D5NZZpbR5jFV:b-8npvpk) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/814c25afa6a7db7d039de94898e3f949faaa5b39/src/operations/executors/graph_executor_test.ts#L76)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

Don't import using dist since this file may move. Use the public facing API by importing test_util from the public package.
</blockquote></details>

Nikhil is right, vs code auto import gives the wrong thing.

import {test_util} from '@tensorflow/tfjs-core';

test_util.expectArraysClose(result, [1]);

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/111)*

**Comment by jsawruk** [comment]
Thanks. I have modified my code to use test_util.

**Comment by pyu10055** [comment]
:lgtm_strong: Thanks!

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/111#-:-LCAoNH20qzGO2K0EHEo:bfdlkw5)*

**Pull request merged**
