### PR TITLE
Add the base class for TensorArray ops

### PR DESCRIPTION
**Pull request by pyu10055**
Implemented the base class that represents the TensorArray.
It also provides the functions for ops (read, write, gather, split, scatter, size, clear).

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/163)

### CODE REVIEW

**Comment by nsthorat** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[src/executor/tensor_array.ts, line 42 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/163#-LG0t0tx1bvwhuiQ6jHq:-LG0t0tx1bvwhuiQ6jHr:bbmra8d) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8d837f88f9f7f76f5bbf68babe6d93477d8cb2ee/src/executor/tensor_array.ts#L42)):*
> ```XML
>       public readonly clearAfterRead: boolean) {}
> 
>   get closed() {
> ```

is this meant to be part of the public API? if only used internally 

---

*[src/executor/tensor_array.ts, line 46 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/163#-LG0uacf89-fgEeZIP5e:-LG0uacf89-fgEeZIP5f:belvbvt) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8d837f88f9f7f76f5bbf68babe6d93477d8cb2ee/src/executor/tensor_array.ts#L46)):*
> ```XML
>   }
> 
>   clearAndClosed() {
> ```

clearAndClose

---

*[src/executor/tensor_array.ts, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/163#-LG0qzex1MtJCcykli5q:-LG0qzex1MtJCcykli5r:b-u4vip3) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8d837f88f9f7f76f5bbf68babe6d93477d8cb2ee/src/executor/tensor_array.ts#L47)):*
> ```XML
> 
>   clearAndClosed() {
>     this.tensors = [];
> ```

should this be disposing tensors? When does that happen?

---

*[src/executor/tensor_array.ts, line 86 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/163#-LG0unwW0RMdl7hM5pCp:-LG0unwW0RMdl7hM5pCq:bbjyxtt) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8d837f88f9f7f76f5bbf68babe6d93477d8cb2ee/src/executor/tensor_array.ts#L86)):*
> ```XML
> 
>   write(index: number, tensor: Tensor) {
>     if (this.closed_) {
> ```

lets remove the getter since you just use the private variable

---

*[src/executor/tensor_array.ts, line 241 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/163#-LG0uv6L6zohFn8e1AoL:-LG0uv6L6zohFn8e1AoM:bf7nxmk) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8d837f88f9f7f76f5bbf68babe6d93477d8cb2ee/src/executor/tensor_array.ts#L241)):*
> ```XML
>       const indices = [0, previousLength, 0];
>       const sizes = [1, length[i], elementPerRow];
>       tensors[i] = slice(tensor, indices, sizes).reshape(this.elementShape);
> ```

this is a leak, you should tidy these methods

---

*[src/executor/tensor_array_test.ts, line 26 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/163#-LG0uzK0-wuRXi86C9kf:-LG0uzK0-wuRXi86C9kg:b3ke586) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8d837f88f9f7f76f5bbf68babe6d93477d8cb2ee/src/executor/tensor_array_test.ts#L26)):*
> ```XML
> const tensor = tensor2d([1], [1, 1], 'int32');
> const tensor2 = tensor2d([2], [1, 1], 'int32');
> describe('ExecutionContext', () => {
> ```

can you add memory unit tests for these? make sure none of the methods leak

---

*[src/executor/tensor_array_test.ts, line 29 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/163#-LG0v22c2_fIuEKBhKub:-LG0v22c2_fIuEKBhKuc:bic9zpm) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8d837f88f9f7f76f5bbf68babe6d93477d8cb2ee/src/executor/tensor_array_test.ts#L29)):*
> ```XML
>   beforeEach(() => {
>     tensorArray =
>         new TensorArray('TA1', 'int32', 10, [1, 1], true, false, false);
> ```

name these variables

---

*[src/executor/tensor_array_test.ts, line 31 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/163#-LG0v0zH7TEOLkymUESB:-LG0v0zH7TEOLkymUESC:bo9el0z) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8d837f88f9f7f76f5bbf68babe6d93477d8cb2ee/src/executor/tensor_array_test.ts#L31)):*
> ```XML
>         new TensorArray('TA1', 'int32', 10, [1, 1], true, false, false);
>   });
>   afterEach(() => {});
> ```

this is unecessary

---

*[src/executor/tensor_array_test.ts, line 163 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/163#-LG1Jf-rEeO2VWiPvrjB:-LG1Jf-rEeO2VWiPvrjC:b-rkbbkk) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8d837f88f9f7f76f5bbf68babe6d93477d8cb2ee/src/executor/tensor_array_test.ts#L163)):*
> ```XML
>     beforeEach(() => {
>       tensorArray =
>           new TensorArray('TA1', 'int32', 3, [2, 2], true, false, false);
> ```

name these arguments here and elsewhere

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/163)*

**Comment by pyu10055** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[src/executor/tensor_array.ts, line 42 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/163#-LG0t0tx1bvwhuiQ6jHq:-LG2-2YZBPBIy-0YDEdm:b-l0mvrs) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8d837f88f9f7f76f5bbf68babe6d93477d8cb2ee/src/executor/tensor_array.ts#L42)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

is this meant to be part of the public API? if only used internally 
</blockquote></details>

yes, tensor array has a close method.

---

*[src/executor/tensor_array.ts, line 46 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/163#-LG0uacf89-fgEeZIP5e:-LG2CFxK2egRku0tW25H:bb7f2mf) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8d837f88f9f7f76f5bbf68babe6d93477d8cb2ee/src/executor/tensor_array.ts#L46)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

clearAndClose
</blockquote></details>

done

---

*[src/executor/tensor_array.ts, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/163#-LG0qzex1MtJCcykli5q:-LG20M_s6tBht5nfPA-3:b-6b9ai0) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8d837f88f9f7f76f5bbf68babe6d93477d8cb2ee/src/executor/tensor_array.ts#L47)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

should this be disposing tensors? When does that happen?
</blockquote></details>

we can do it here, TF implementation does not dispose these tensors, it depends on the graph executor to dispose.

---

*[src/executor/tensor_array.ts, line 86 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/163#-LG0unwW0RMdl7hM5pCp:-LG20we60r3Zf183_Zvm:bkkgxn8) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8d837f88f9f7f76f5bbf68babe6d93477d8cb2ee/src/executor/tensor_array.ts#L86)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

lets remove the getter since you just use the private variable
</blockquote></details>

the get method is for external access to the state of the tensor array.

---

*[src/executor/tensor_array.ts, line 241 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/163#-LG0uv6L6zohFn8e1AoL:-LG2C2Rq0hU-s1ThjG77:b1jxzi3) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8d837f88f9f7f76f5bbf68babe6d93477d8cb2ee/src/executor/tensor_array.ts#L241)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

this is a leak, you should tidy these methods
</blockquote></details>

good catch, done.

---

*[src/executor/tensor_array_test.ts, line 26 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/163#-LG0uzK0-wuRXi86C9kf:-LG2HdAh-nnDXxfl4OgD:bb7f2mf) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8d837f88f9f7f76f5bbf68babe6d93477d8cb2ee/src/executor/tensor_array_test.ts#L26)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

can you add memory unit tests for these? make sure none of the methods leak
</blockquote></details>

done

---

*[src/executor/tensor_array_test.ts, line 29 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/163#-LG0v22c2_fIuEKBhKub:-LG2C6maBBXIZhQZrSgo:bb7f2mf) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8d837f88f9f7f76f5bbf68babe6d93477d8cb2ee/src/executor/tensor_array_test.ts#L29)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

name these variables
</blockquote></details>

done

---

*[src/executor/tensor_array_test.ts, line 31 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/163#-LG0v0zH7TEOLkymUESB:-LG2C8VW0I5CfldddeFX:b-csbfe) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8d837f88f9f7f76f5bbf68babe6d93477d8cb2ee/src/executor/tensor_array_test.ts#L31)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

this is unecessary
</blockquote></details>

added tensor array close method to afterEach

---

*[src/executor/tensor_array_test.ts, line 163 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/163#-LG1Jf-rEeO2VWiPvrjB:-LG2CDXH7mf52yZX7yz8:bb7f2mf) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8d837f88f9f7f76f5bbf68babe6d93477d8cb2ee/src/executor/tensor_array_test.ts#L163)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

name these arguments here and elsewhere
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/163)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[src/executor/tensor_array.ts, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/163#-LG0qzex1MtJCcykli5q:-LG5i0_e2OJmCWK_Af5P:bmj2dvm) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8d837f88f9f7f76f5bbf68babe6d93477d8cb2ee/src/executor/tensor_array.ts#L47)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

we can do it here, TF implementation does not dispose these tensors, it depends on the graph executor to dispose.
</blockquote></details>

Sure, that makes sense. They also have finalization and we don't so it's not the fairest comparison.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/163#-:-LG5ij5xB2i8wft9PqnX:b-jbsf8z)*

**Comment by nsthorat** [comment]
FYI you have a failing presubmit, make sure to fix that before merging.

**Pull request merged**
