### PR TITLE
added StridedSlice op

### PR DESCRIPTION
**Pull request by kylemcdonald**
I checked this by using the Dockerfile mentioned in this PR https://github.com/tensorflow/tfjs/issues/305 but modified to replace `git clone --depth=1 https://github.com/tensorflow/tfjs-converter.git` with `git clone --depth=1 -b stridedSlice https://github.com/kylemcdonald/tfjs-converter.git`. Then I tried to convert a SavedModel that includes a StridedSlice operation:

```
$ docker run -it --mount type=bind,src="$(pwd)",dst=/root/mount tfjs bash
cd ~/mount && tensorflowjs_converter \
	--input_format=tf_saved_model \
	--output_node_names='resfcn256/Conv2d_transpose_16/Sigmoid' \
	saved_model \
	output
```

And it seems to work:

```
/opt/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
WARNING:tensorflow:From /opt/conda/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
2018-05-16 19:36:23.097294: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Converted 245 variables to const ops.
2018-05-16 19:36:26.562328: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:221] Return status of optimizer model_pruner: OK. Graph size before: 973 nodes, 1033 edges. Graph size after: 728 nodes, 788 edges.
2018-05-16 19:36:26.562370: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:221] Return status of optimizer constant folding: OK. Graph size before: 728 nodes, 788 edges. Graph size after: 728 nodes, 788 edges.
2018-05-16 19:36:26.562379: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:221] Return status of optimizer arithmetic_optimizer: OK. Graph size before: 728 nodes, 788 edges. Graph size after: 537 nodes, 788 edges.
2018-05-16 19:36:26.562386: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:221] Return status of optimizer dependency_optimizer: OK. Graph size before: 537 nodes, 788 edges. Graph size after: 536 nodes, 764 edges.
2018-05-16 19:36:26.562393: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:221] Return status of optimizer model_pruner: OK. Graph size before: 536 nodes, 764 edges. Graph size after: 536 nodes, 764 edges.
2018-05-16 19:36:26.562400: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:221] Return status of optimizer constant folding: OK. Graph size before: 536 nodes, 764 edges. Graph size after: 536 nodes, 764 edges.
2018-05-16 19:36:26.562406: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:221] Return status of optimizer arithmetic_optimizer: OK. Graph size before: 536 nodes, 764 edges. Graph size after: 536 nodes, 764 edges.
2018-05-16 19:36:26.562413: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:221] Return status of optimizer dependency_optimizer: OK. Graph size before: 536 nodes, 764 edges. Graph size after: 536 nodes, 764 edges.
Writing weight file output/tensorflowjs_model.pb...
```

But I still need to try getting it running in the browser next.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/131)

### CODE REVIEW

**Comment by pyu10055** [comment]
:lgtm_strong: Thanks for doing this.
Your change would enable the python converter to convert the StridedSlice op, but js interpreter needs add the op support.

check the   src/operations/executors/slice_join_executor.ts

Unfortunately, to do that you need to wait for tfjs-core new npm release with the StridedSlice change.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/operations/op_list/slice_join.json, line 168 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/131#-LCeVUm197LaPTb6N-_k:-LCeVUm197LaPTb6N-_l:b-8m4v03) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/d099db6a6025c086d13c4de1f9c2091bd7ee5ef6/src/operations/op_list/slice_join.json#L168)):*
> ```JSON
>       },
>       {
>         "tfInputIndex": 4,
> ```

beginMask and endMask are not inputs they are attributes.

{
        "tfParamName": "begin_mask",
        "dlParamName": "beginMask",
        "type": "number",
        "defaultValue": 0
      },
{
        "tfParamName": "end_mask",
        "dlParamName": "endMask",
        "type": "number",
        "defaultValue": 0
      }

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/131#-:-LCeUdj74-js8qxJxzKf:b-vx0nxs)*

**Comment by pyu10055** [comment]
we can merge your change first once you update the json file, I can add the interpreter changes separately.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/131#-:-LCeXMAwE9195aUL5b9L:bif8i0s)*

**Comment by kylemcdonald** [comment]
Great, I understand. I just made the change here https://github.com/tensorflow/tfjs/issues/292#issuecomment-389664162

And thought I was done, but then I see: `tf-converter.js:8330 Uncaught (in promise) TypeError: Node type stridedSlice is not implemented` and I realize it's because of the missing implementation in `slice_join_executor.ts`.

I think the implementation looks like:

```js
    case 'stridedSlice': {
      const begin = getParamValue('begin', node, tensorMap, context) as number[];
      const end = getParamValue('end', node, tensorMap, context) as number[];
      const strides = getParamValue('strides', node, tensorMap, context) as number[];
      const beginMask = getParamValue('beginMask', node, tensorMap, context) as number;
      const endMask = getParamValue('endMask', node, tensorMap, context) as number;
      return [tfc.stridedSlice(
          getParamValue('x', node, tensorMap, context) as tfc.Tensor, begin,
          end, strides, beginMask, endMask)];
    }
```

Is that right?

**Comment by pyu10055** [comment]
yes, your executor implementation looks good.

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/131#-:-LCg49s23UthEyiwJRjg:br8eh9p)*

**Comment by pyu10055** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/131)*

**Pull request merged**
