### PR TITLE
fix: No matching distribution found for tensorflow==1.12.0

### PR DESCRIPTION
**Pull request by chenqing**
see here [tfjs-converter: may update tensorflow's version](https://github.com/tensorflow/tfjs/issues/1261#issue-411511934)

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/309)

### CODE REVIEW

**Comment by bidakos** [comment]
Any update on it?

Could not find a version that satisfies the requirement tensorflow==1.12.0 (from tensorflowjs) (from versions: 1.13.0rc1, 1.13.0rc2)
No matching distribution found for tensorflow==1.12.0 (from tensorflowjs)

**Comment by chenqing** [comment]
> Any update on it?
> 
> Could not find a version that satisfies the requirement tensorflow==1.12.0 (from tensorflowjs) (from versions: 1.13.0rc1, 1.13.0rc2)
> No matching distribution found for tensorflow==1.12.0 (from tensorflowjs)

just update  some packages version in requirements.txt

**Comment by pyu10055** [comment]
tensorflow current stable release is 1.12.0
https://pypi.org/project/tensorflow/1.12.0/

**Comment by chenqing** [comment]
> tensorflow current stable release is 1.12.0
> https://pypi.org/project/tensorflow/1.12.0/

the main reason is tensorflow 1.12.0 not support  Python 3.7. when use tfjs-converter in this python version may cause this problem.

so just wait for 1.13.0 release.

**Comment by chenqing** [comment]
now tensorflow  1.13.1 has released.
https://pypi.org/project/tensorflow/1.13.1/

**Comment by pyu10055** [comment]
there are some breaking changes in 1.13.x for tfjs converter. You can see the tests are failing, we are planning to upgrade to 1.13 in the next couple days.

**Comment by chenqing** [comment]
> there are some breaking changes in 1.13.x for tfjs converter. You can see the tests are failing, we are planning to upgrade to 1.13 in the next couple days.

ok

**Pull request closed without merging**
