### PR TITLE
Inference model update

### PR DESCRIPTION
**Pull request by pyu10055**
update the frozen model according to inference model interface form the core

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/144)

### CODE REVIEW

**Comment by caisq** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[src/executor/frozen_model.ts, line 177 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/144#-LDtCeY52lEAXTHWpqQB:-LDtCeY52lEAXTHWpqQC:bygil9o) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8ddc76d65ed240a8a3923fbd900ca099f1abfa82/src/executor/frozen_model.ts#L177)):*
> ```
> inputs instanceof Array
> ```

Probably better to use Array.isArray().

http://perfectionkills.com/instanceof-considered-harmful-or-how-to-write-a-robust-isarray/

---

*[src/executor/frozen_model.ts, line 188 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/144#-LDtDk1u7xRAoxI4hWqr:-LDtDk1u7xRAoxI4hWqs:b-ddo3kv) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8ddc76d65ed240a8a3923fbd900ca099f1abfa82/src/executor/frozen_model.ts#L188)):*
> ```
> outputs instanceof Array
> ```

Array.isArray()

---

*[src/executor/frozen_model.ts, line 218 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/144#-LDtDqHH4NqkcHnbo2YM:-LDtDqHH4NqkcHnbo2YN:b-ddo3kv) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8ddc76d65ed240a8a3923fbd900ca099f1abfa82/src/executor/frozen_model.ts#L218)):*
> ```
> outputs instanceof Array
> ```

Array.isArray()

---

*[src/executor/frozen_model_test.ts, line 99 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/144#-LDtCOGeDA-cgqHpbbAI:-LDtCOGeDA-cgqHpbbAJ:b-vt7355) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8ddc76d65ed240a8a3923fbd900ca099f1abfa82/src/executor/frozen_model_test.ts#L99)):*
> ```
>  {}
> ```

Instead of using an empty Object, just remove it?

---

*[src/executor/frozen_model_test.ts, line 135 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/144#-LDtDuuW-ttGUD5NV0kG:-LDtDuuW-ttGUD5NV0kH:bhdmx0r) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8ddc76d65ed240a8a3923fbd900ca099f1abfa82/src/executor/frozen_model_test.ts#L135)):*
> ```
> output instanceof Array).toBeTruthy();
> ```

expect(Array.isArray(output)).toEqual(true);

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/144)*

**Comment by pyu10055** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/executor/frozen_model.ts, line 177 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/144#-LDtCeY52lEAXTHWpqQB:-LDw5ZwADhXt30CQuTxB:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8ddc76d65ed240a8a3923fbd900ca099f1abfa82/src/executor/frozen_model.ts#L177)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> inputs instanceof Array
> ```

Probably better to use Array.isArray().

http://perfectionkills.com/instanceof-considered-harmful-or-how-to-write-a-robust-isarray/
</blockquote></details>

Done.

---

*[src/executor/frozen_model.ts, line 188 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/144#-LDtDk1u7xRAoxI4hWqr:-LDw5_PP-YF_FlOv6wlW:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8ddc76d65ed240a8a3923fbd900ca099f1abfa82/src/executor/frozen_model.ts#L188)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> outputs instanceof Array
> ```

Array.isArray()
</blockquote></details>

Done.

---

*[src/executor/frozen_model.ts, line 218 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/144#-LDtDqHH4NqkcHnbo2YM:-LDw75X47WC8MwpXzUc0:btgoe4m) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8ddc76d65ed240a8a3923fbd900ca099f1abfa82/src/executor/frozen_model.ts#L218)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> outputs instanceof Array
> ```

Array.isArray()
</blockquote></details>

rafactored the code a bit.

---

*[src/executor/frozen_model_test.ts, line 99 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/144#-LDtCOGeDA-cgqHpbbAI:-LDw7Cdg3ouQ8sAq-vwT:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8ddc76d65ed240a8a3923fbd900ca099f1abfa82/src/executor/frozen_model_test.ts#L99)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
>  {}
> ```

Instead of using an empty Object, just remove it?
</blockquote></details>

Done

---

*[src/executor/frozen_model_test.ts, line 135 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/144#-LDtDuuW-ttGUD5NV0kG:-LDw7ar00nDNqrdm45Pw:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/8ddc76d65ed240a8a3923fbd900ca099f1abfa82/src/executor/frozen_model_test.ts#L135)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> output instanceof Array).toBeTruthy();
> ```

expect(Array.isArray(output)).toEqual(true);
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/144)*

**Comment by pyu10055** [comment]
Thanks for the review, PTAL.

---

Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/144#-:-LDw7tr8A_BRp2wEcNHH:blk23h7)*

**Comment by caisq** [comment]
:lgtm_strong:

---

Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/executor/frozen_model.ts, line 223 at r2](https://reviewable.io/reviews/tensorflow/tfjs-converter/144#-LDwBeKG690AAvYJde2N:-LDwBeKG690AAvYJde2O:b1twuyx) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/c6765728cb52e3d7a523a90245cde1f447b88ccd/src/executor/frozen_model.ts#L223)):*
> ```
> (
> ```

These parentheses are superfluous, strictly speaking.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/144#-:-LDwBlbA9W6M69sWffhl:b-jbsf8z)*

**Pull request merged**
