### PR TITLE
adds documentation for output .h5 format

### PR DESCRIPTION
**Pull request by bileschi**
(documentation)  Adds documentation for output option.  Fixes a line breaking issue with flag names being broken into two lines on narrow screens.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/153)

### CODE REVIEW

**Comment by pyu10055** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[README.md, line 89 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/153#-LEz4Ri-Dyw3OykGplQg:-LEz4Ri-Dyw3OykGplQh:b-zae48u) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/ca9db36d8763d1b0b7a33be0e0387723283626dc/README.md#L89)):*
> ```Markdown
> |`--input_format`     | The format of input model, use tf_saved_model for SavedModel, tf_frozen_model for frozen model, tf_session_bundle for session bundle, tf_hub for TensorFlow Hub module and keras for Keras HDF5. |
> |<nobr>`--output_node_names`</nobr>| The names of the output nodes, separated by commas.|
> |`--output_format`| The desired output format.  Must be `tensorflowjs` (the default) or `keras`.  |
> ```

does this flag allow outputting keras format for SavedModel files?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/153)*

**Comment by caisq** [comment]
:lgtm_strong:

---

Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[README.md, line 89 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/153#-LEz4Ri-Dyw3OykGplQg:-LEzAeeCDmDYYssyFIKm:bp27sdp) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/ca9db36d8763d1b0b7a33be0e0387723283626dc/README.md#L89)):*
<details><summary><i>Previously, bileschi (Stanley Bileschi) wrote…</i></summary><blockquote>

Not currently.  Not all pairs of input-output are supported.  There are appropriate error messages for when an unsupported pair is selected.
</blockquote></details>

--output_format=keras is only for converting tensorflowjs format to keras H5 format.

---

*[README.md, line 90 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/153#-LEzARTO8B-SE3VF9C2U:-LEzARTO8B-SE3VF9C2V:b7z3i6z) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/ca9db36d8763d1b0b7a33be0e0387723283626dc/README.md#L90)):*
> ```
> ,
> ```

nit: comma -> period.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/153#-:-LEzAk07AIIVxS0Kqqx6:b-jbsf8z)*

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Review status: :shipit: complete! 2 of 1 LGTMs obtained

---

*[README.md, line 89 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/153#-LEz4Ri-Dyw3OykGplQg:-LEzCWcm0qpokl9LbUlV:bojd92l) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/ca9db36d8763d1b0b7a33be0e0387723283626dc/README.md#L89)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

--output_format=keras is only for converting tensorflowjs format to keras H5 format.
</blockquote></details>

how about renaming it to `keras_h5` to be more explicit?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/153#-:-LEzDIBR5s4o67hh_fuN:b-jbsf8z)*

**Comment by pyu10055** [comment]
Review status: :shipit: complete! 2 of 1 LGTMs obtained

---

*[README.md, line 89 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/153#-LEz4Ri-Dyw3OykGplQg:-LEzGIsBBOkeD21_1EoF:b-ftxnrf) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/ca9db36d8763d1b0b7a33be0e0387723283626dc/README.md#L89)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

how about renaming it to `keras_h5` to be more explicit?
</blockquote></details>

this is bit confusing, since the input_format does not contain tensorflowjs.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/153)*

**Comment by caisq** [comment]
Review status: :shipit: complete! 2 of 1 LGTMs obtained

---

*[README.md, line 89 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/153#-LEz4Ri-Dyw3OykGplQg:-LEzIKaPAxrhVzsC0z1_:b-3a4xgi) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/ca9db36d8763d1b0b7a33be0e0387723283626dc/README.md#L89)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

this is bit confusing, since the input_format does not contain tensorflowjs.
</blockquote></details>

input_format does allow tensorflowjs. https://github.com/tensorflow/tfjs-converter/blob/master/python/tensorflowjs/converters/converter.py#L139

But good point, Ping. Stan, can you add it to this markdown table, in the row above? 

Thanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/153)*

**Comment by bileschi** [comment]
Review status: :shipit: complete! 2 of 1 LGTMs obtained

---

*[README.md, line 89 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/153#-LEz4Ri-Dyw3OykGplQg:-LEzBUIBE5MA8bii5bW2:b-idikc) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/ca9db36d8763d1b0b7a33be0e0387723283626dc/README.md#L89)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

maybe be more specific that if the input_format is tensorflowjs, it can only be converted to keras.
</blockquote></details>

Given the number of input / output combinations I've added a table for clarity

---

*[README.md, line 90 at r1](https://reviewable.io/reviews/tensorflow/tfjs-converter/153#-LEzARTO8B-SE3VF9C2U:-LEzBQ080oxpG7vtdnx2:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/ca9db36d8763d1b0b7a33be0e0387723283626dc/README.md#L90)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> ,
> ```

nit: comma -> period.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/153)*

**Comment by pyu10055** [comment]
:lgtm_strong: Thanks!

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! 3 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/153#-:-LEzwa32-ILmjkrs3yAO:bfdlkw5)*

**Pull request merged**
