### PR TITLE
implemented Control flow ops 

### PR DESCRIPTION
**Pull request by pyu10055**
Created op executor for merge/switch/enter/exit/nextIteration/loopCond

Updated the op execute method signature to allow providing the ExecutionContext that tracks the current frame and iteration.

Add a demo page that showcase the while_loop graph execution.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/81)

### CODE REVIEW

**Comment by nsthorat** [comment]
Awesome work. One comment that's pretty important, I'd love to talk about this over video chat if you have some time tomorrow (when Daniel is back since he has opinions about this).

---

Review status: 0 of 49 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[demo/control_flow/index.html, line 1 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/81#-L9jtQXw2-nURDdQ1jPs:-L9jtQXw2-nURDdQ1jPt:b-cjfuvy) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/48328f01fd1f30187ab1a771605873c9086a26b3/demo/control_flow/index.html#L1)):*
> ```HTML
>

**Comment by nsthorat** [comment]
Review status: 0 of 49 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/operations/executors/control_executor.ts, line 39 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/81#-L9jtnp-CRwbYZpnFGTG:-L9lNcK-6WYTMumyOIaP:b28jqn1) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/48328f01fd1f30187ab1a771605873c9086a26b3/src/operations/executors/control_executor.ts#L39)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

curious what is the benefit of leaking up, somewhere we have to await the promise, why not do it in the op executor?
</blockquote></details>

I guess it depends on what you mean by leaking up. What I'm saying is the promise has to show itself to the user (if you await, you need to be in an async function that returns a promise, so transitively the call site to execute() or some other analogous method would have to be async).

Does that make sense?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/81)*

**Comment by pyu10055** [comment]
Review status: 0 of 49 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/operations/executors/control_executor.ts, line 39 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/81#-L9jtnp-CRwbYZpnFGTG:-L9lPdK8DBHD9E5mSOX0:bn9pcat) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/48328f01fd1f30187ab1a771605873c9086a26b3/src/operations/executors/control_executor.ts#L39)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

I guess it depends on what you mean by leaking up. What I'm saying is the promise has to show itself to the user (if you await, you need to be in an async function that returns a promise, so transitively the call site to execute() or some other analogous method would have to be async).

Does that make sense?
</blockquote></details>

Got it, I thought you mean the logic. yeah, it make sense to update the signature to return promise<Tensor[]> 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/81)*

**Comment by pyu10055** [comment]
Review status: 0 of 54 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[demo/control_flow/index.html, line 1 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/81#-L9jtQXw2-nURDdQ1jPs:-LABd0m94IPDq7bT5sTh:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/48328f01fd1f30187ab1a771605873c9086a26b3/demo/control_flow/index.html#L1)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

2018, also this license should be google LLC here and everywhere else
</blockquote></details>

Done.

---

*[src/operations/executors/control_executor.ts, line 39 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/81#-L9jtnp-CRwbYZpnFGTG:-LABdCkMBn8-KA8PTWOk:bhs4h0x) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/48328f01fd1f30187ab1a771605873c9086a26b3/src/operations/executors/control_executor.ts#L39)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

Got it, I thought you mean the logic. yeah, it make sense to update the signature to return promise<Tensor[]> 
</blockquote></details>

Sorry for the delay, the PR is ready to be review again.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/81)*

**Comment by dsmilkov** [comment]
:lgtm_strong: Minor comments. Nice work Ping!

---

Reviewed 8 of 56 files at r1, 58 of 62 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[demo/package.json, line 16 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/81#-LAUPxy13z_VfzZblV0N:-LAUPxy13z_VfzZblV0O:b-y59m66) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/b1835fc6722a6709fddb0725b6c3e52ffb8249b1/demo/package.json#L16)):*
> ```JSON
>     "control_flow": "NODE_ENV=development parcel --no-hmr --open control_flow/index.html ",
>     "build_mobilenet": "NODE_ENV=production parcel build mobilenet/index.html  --no-minify --public-url /",
>     "build_control_flow": "NODE_ENV=production parcel build control_flw/index.html  --no-minify --public-url /"
> ```

typo: s/control_flw/control_flow. Btw, do you use the build_* rules at this point? If you are using their watch versions above, remove the 2 build_* rules.

---

*[demo/control_flow/index.html, line 34 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/81#-LAUQOrn4ZuzoJXLOr58:-LAUQOrn4ZuzoJXLOr59:b-dqhzjm) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/b1835fc6722a6709fddb0725b6c3e52ffb8249b1/demo/control_flow/index.html#L34)):*
> ```HTML
>   <h1>TensorFlow.js Converter: ControlFlow</h1>
>   <h3>This example uses a Tensorflow model that is generated by tf.while_loop method.</h3>
> ```

Add a short sentence what this demo demonstrates and what the person what opens this page should do. E.g. Should the user play with the inputs below and see the execution in TF.js below?

---

*[demo/control_flow/README.md, line 3 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/81#-LAUR6wIEv5qlm1gSBOM:-LAUR6wIEv5qlm1gSBON:b-gtcbag) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/b1835fc6722a6709fddb0725b6c3e52ffb8249b1/demo/control_flow/README.md#L3)):*
> ```Markdown
> # TensorFlow SavedModel Import Demo
> 
> This demo imports the a TensorFlow model that is generated by tf.while_loop
> ```

remove extra `a`

---

*[demo/control_flow/README.md, line 9 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/81#-LAURGNO5JLjQOacASY-:-LAURGNO5JLjQOacASY0:b-k7ed49) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/b1835fc6722a6709fddb0725b6c3e52ffb8249b1/demo/control_flow/README.md#L9)):*
> ```Markdown
> 
> The following commands will start a web server on `localhost:1234` and open
> a browser page with the demo.
> ```

Say something actionable - a reason for the user to open the demo. Maybe, something like:
The demo allows you to change the conditions of the loop interactively and observe the execution, right in the browser.

---

*[src/executor/execution_context.ts, line 21 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/81#-LAUWdM_03OgwGbCp8Vj:-LAUWdM_03OgwGbCp8Vk:bp43yq3) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/b1835fc6722a6709fddb0725b6c3e52ffb8249b1/src/executor/execution_context.ts#L21)):*
> ```XML
> import {NamedTensorsMap} from '../data';
> 
> export interface ExecutionContextId {
> ```

consider renaming this to ExecutionContextInfo

---

*[src/executor/execution_context.ts, line 23 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/81#-LAUWRBo56r2T1MktATG:-LAUWRBo56r2T1MktATH:bplv8ch) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/b1835fc6722a6709fddb0725b6c3e52ffb8249b1/src/executor/execution_context.ts#L23)):*
> ```XML
> export interface ExecutionContextId {
>   id: number;
>   frameName: string;
> ```

Add small comments to give some context what id vs frameName vs iterationId means

---

*[src/executor/execution_context.ts, line 29 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/81#-LAUXkt2EeVSJ0oyT_mx:-LAUXkt2EeVSJ0oyT_my:b-o5vsz7) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/b1835fc6722a6709fddb0725b6c3e52ffb8249b1/src/executor/execution_context.ts#L29)):*
> ```XML
> /**
>  * ExecutionContext captures the runtime environment of the node. It keeps
>  * track of the current frame and iteration for the control flow ops.
> ```

will be good to give an example of where/which ops are using this for what reason.

---

*[src/executor/frozen_model.ts, line 134 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/81#-LAUWoZnB6o5xjwlrlKJ:-LAUWoZnB6o5xjwlrlKK:b1o2156) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/b1835fc6722a6709fddb0725b6c3e52ffb8249b1/src/executor/frozen_model.ts#L134)):*
> ```XML
> 
>   /**
>    * Executes infrerence for the model for given input tensors in async fashion,
> ```

typo: inference

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/81#-:-LAUYC2b9vDO3d-eUalw:b9pfcvz)*

**Pull request merged**
