### PR TITLE
Enforce clean virtualenv for tensorflowjs pip install

### PR DESCRIPTION
**Pull request by caisq**
Fixes https://github.com/tensorflow/tfjs/issues/1546

This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/365)

### CODE REVIEW

**Comment by dsmilkov** [comment]
Thanks! We can improve/change this message later to reflect our final decision about which TF version we use, but given the current state, this is a step is the right direction.

**Comment by caisq** [comment]
FYI @pyu10055 @nsthorat Thank you for the reviews. I manually tested if this actually works and prevents existing tensorflow 1.x installs to be upgraded to 2.x. Unfortunately, so far the answer is no. The reason is the newly added checks run only when the pip wheel is *built*, but not when its *installed*. I'll keep digging a solution for this. But it's possible that this is not actually feasible and we'd have to warn the users to be careful or to use the `pip install --no-deps tensorflowjs` command.

**Comment by dsmilkov** [comment]
I see. Looking for an alternative SGTM, if not we can remove the dependency altogether and ask people to install tensorflow before installing this one.

**Comment by caisq** [comment]
Closing this PR as 1) this doesn't do what it intends to do and 2) as we discussed among us offline, we'l move to a model in which tensorflowjs doesn't include tensorflow as a required pip dependency.

**Comment by dsmilkov** [comment]
Sounds good @caisq Thanks for the investigation!

**Pull request closed without merging**
