### PR TITLE
Update tfjs-core version to 0.6.0

### PR DESCRIPTION
**Pull request by dsmilkov**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/60)

### CODE REVIEW

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/60#-:-L8oDlqX17t2gh57REs-:b-jbsf8z)*

**Comment by pyu10055** [comment]
:lgtm_strong: should we push a new npm version out?

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/60#-:-L8oaIPQBkIhjwFbCyXt:b2xmcez)*

**Comment by dsmilkov** [comment]
I'll release 0.1.1 now

**Comment by dsmilkov** [comment]
Actually, Ping can you release a 0.1.1 when you get a chance? No rush. The npm installation on this laptop is broken.

**Pull request merged**
