### PR TITLE
Add avgPool3d & maxPool3d ops to graph model executor

### PR DESCRIPTION
**Pull request by syt123450**
This PR add add `avgPool3d` & `maxPool3d` ops to executor, which makes graph model support `AvgPool3D` op and `MaxPool3D` op.

Features in this PR:
* Register `AvgPool3D` and `MaxPool3D` op in convolution op list
* Map `AvgPool3D` to `avgPool3d`, `MaxPool3D` to `maxPool3d` in convolution executor
* Add relative tests for the op mapping
* Add new ops to markdown documentation

**Note:**
This PR depends on [tensorflow/tfjs-core#1778](https://github.com/tensorflow/tfjs-core/pull/1778), which adds `maxPool3d` op, `avgPool3d` op, and exports `Tensor5D` type.

**Reference:**
* [tf.nn.avg_pool3d TensorFlow Python API](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/nn/avg_pool3d)
* [tf.nn.max_pool3d TensorFlow Python API](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/nn/max_pool3d)

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/375)

### CODE REVIEW

**Comment by syt123450** [comment]
Hi @pyu10055 , thanks for the review.

This PR depend on the features in [tensorflow/tfjs-core#1778](https://github.com/tensorflow/tfjs-core/pull/1778), which has not been checked in, may be we can update the version later? I would like to help update the deps when the tfjs-core released the features.

**Comment by dsmilkov** [comment]
@googlebot I consent.

**Comment by dsmilkov** [comment]
Thanks for the contribution! I updated core's version to 1.2.8 so the CI testing should pass and we'll merge this right after.

**Comment by syt123450** [comment]
Thanks for the review @pyu10055 @dsmilkov !

**Pull request merged**
