### PR TITLE
support aggressive intermediate tensor disposal

### PR DESCRIPTION
**Pull request by pyu10055**
fix https://github.com/tensorflow/tfjs/issues/719

Ref count is used to track each tensor, the ref count is determined by the dependent node.
The ref count is decreased when any of dependent nodes is executed. There is a main caveat for
graph with control flow op, we will only decrease the parent ref count, if it is in the same execution
context as the child node.
 
To determine if an tensor is ready to be disposed, following rules are checked:

1. The tensor is not input or weight tensors
2. The tensor ref count is 0
3. The tensor is not an output of a control flow type node

|DeepLabV3 model |peak GPU memory (bytes)|
|-|-|
|before|1326701472|
|after|73078664|

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/214)

### CODE REVIEW

**Comment by 24rochak** [comment]
I am trying to convert the frozen inference graph of [DeepLab](http://download.tensorflow.org/models/deeplabv3_mnv2_pascal_train_aug_2018_01_29.tar.gz) hosted at their [model zoo](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md). 

The conversion was successful but when I load the model I get the following output : 

`Error importing the graph: block_shape must be positive for 'MobilenetV2/expanded_conv_7/depthwise/depthwise/SpaceToBatchND' (op: 'SpaceToBatchND') with input shapes: [1,?,?,384], [2], [2,2] and with computed input tensors: input[1] = <0 0>, input[2] = <[0 0][0 0]>.
Process finished with exit code 2`

The script which I use for loading the converted is : 

    graph_def = None
    graph = None
    model_file = "tensorflowjs_model.pb"
    
    print('Loading graph definition ...', file=sys.stderr)
    try:
        with tf.gfile.GFile(model_file, "rb") as f:
            graph_def = tf.GraphDef()
            graph_def.ParseFromString(f.read())
    except BaseException as e:
        parser.exit(2, 'Error loading the graph definition: {}'.format(str(e)))
    
    print('Importing graph ...', file=sys.stderr)
    try:
        assert graph_def is not None
        with tf.Graph().as_default() as graph:  # type: tf.Graph
            tf.import_graph_def(
                graph_def,
                name=''
            )
    except BaseException as e:
    parser.exit(2, 'Error importing the graph: {}'.format(str(e)))

**Comment by pyu10055** [comment]
Hi @24rochak, can you create an issue on [here](https://github.com/tensorflow/tfjs/issues). The PR is not really related to the problem you raised. Thanks.

**Comment by nsthorat** [comment]
Did you push your changes? I don't see the fixes from the comments.

**Comment by pyu10055** [comment]
> Did you push your changes? I don't see the fixes from the comments.

sorry, just pushed the changes.

**Comment by dsmilkov** [comment]
Hi Ping, can you update the PR description with info about the difference in peak memory usage (see [tf.profile](https://js.tensorflow.org/api/latest/#profile)) before and after this PR, measured on several of the model where memory was an issue before. Thank you!

**Pull request merged**
