### PR TITLE
Checkpoint support

### PR DESCRIPTION
**Pull request by pyu10055**
Add support for checkpoint model format in the python converter.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-converter/84)

### CODE REVIEW

**Comment by nsthorat** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[README.md, line 10 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9kWRuP99FeJubebEb0:-L9kWRuP99FeJubebEb1:b6yqnzj) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/56f9bf55e878ca4bd37701414cf634693ccc67c5/README.md#L10)):*
> ```Markdown
> into the browser and run inference through [TensorFlow.js](https://js.tensorflow.org).
> 
> (Note: TensorFlow has deprecated checkpoint model format, please switch to SavedModel immediately.)
> ```

remove "immediately"

---

*[README.md, line 126 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9kbeS1CYcvHXYSrfVz:-L9kbeS1CYcvHXYSrfW-:b-kzksg2) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/82a33eea7066c3a1b7fcbdf4e6c68ce32d740eab/README.md#L126)):*
> ```Markdown
> 
> ```typescript
> import * as tfc from '@tensorflow/tfjs-core';
> ```

let's import union here

---

*[README.md, line 130 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9kbbQJ-8y8r11FCyTT:-L9kbbQJ-8y8r11FCyTU:b-jh9jp2) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/82a33eea7066c3a1b7fcbdf4e6c68ce32d740eab/README.md#L130)):*
> ```Markdown
> const weightManifestUrl = "https://example.org/model/weights_manifest.json";
> const manifest = await fetch(weightManifestUrl);
> this.weightManifest = await manifest.clone().json();
> ```

why do you need to clone this?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84)*

**Comment by davidsoergel** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[README.md, line 10 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9kbkNt9OmtiLHyoqf-:-L9kbkNt9OmtiLHyoqf0:b-mrvqa4) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/82a33eea7066c3a1b7fcbdf4e6c68ce32d740eab/README.md#L10)):*
> ```
> checkpoint model
> ```
I've never heard this term before, and it's confusing because SavedModel is a model with a checkpoint in it.  Let's call this session_bundle throughout.

---

*[python/tensorflowjs/converters/tf_saved_model_conversion.py, line 163 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9kcGUm91FG22EM3LJM:-L9kcGUm91FG22EM3LJN:buyvcx9) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/82a33eea7066c3a1b7fcbdf4e6c68ce32d740eab/python/tensorflowjs/converters/tf_saved_model_conversion.py#L163)):*
> ```Python
>       separated string format. Defaulted to 'serve'
>   """
> ```

This would be a good place to print a deprecation warning.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84)*

**Comment by pyu10055** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 10 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9kWRuP99FeJubebEb0:-L9krX3WBQ3PvGTKI-P1:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/56f9bf55e878ca4bd37701414cf634693ccc67c5/README.md#L10)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

remove "immediately"
</blockquote></details>

Done.

---

*[README.md, line 10 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9kbkNt9OmtiLHyoqf-:-L9krYL100NXvfyLcctl:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/82a33eea7066c3a1b7fcbdf4e6c68ce32d740eab/README.md#L10)):*
<details><summary><i>Previously, davidsoergel (David Soergel) wrote…</i></summary><blockquote>

> ```
> checkpoint model
> ```
I've never heard this term before, and it's confusing because SavedModel is a model with a checkpoint in it.  Let's call this session_bundle throughout.
</blockquote></details>

Done.

---

*[README.md, line 126 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9kbeS1CYcvHXYSrfVz:-L9krk-bAV4c7v5D-sZU:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/82a33eea7066c3a1b7fcbdf4e6c68ce32d740eab/README.md#L126)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

let's import union here
</blockquote></details>

Done.

---

*[README.md, line 130 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9kbbQJ-8y8r11FCyTT:-L9krkMh1sQ-vp-w6ABs:b-hfpv0l) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/82a33eea7066c3a1b7fcbdf4e6c68ce32d740eab/README.md#L130)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

why do you need to clone this?
</blockquote></details>

removed

---

*[python/tensorflowjs/converters/tf_saved_model_conversion.py, line 163 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9kcGUm91FG22EM3LJM:-L9krvuGEA9hSGrRO-5X:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/82a33eea7066c3a1b7fcbdf4e6c68ce32d740eab/python/tensorflowjs/converters/tf_saved_model_conversion.py#L163)):*
<details><summary><i>Previously, davidsoergel (David Soergel) wrote…</i></summary><blockquote>

This would be a good place to print a deprecation warning.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84)*

**Comment by davidsoergel** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 10 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9kbkNt9OmtiLHyoqf-:-L9kzDv95bKIAIf0j_5I:b-soqscz) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/82a33eea7066c3a1b7fcbdf4e6c68ce32d740eab/README.md#L10)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

A few instances are changed but there are a bunch more...

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84)*

**Comment by pyu10055** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 10 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9kbkNt9OmtiLHyoqf-:-L9lNyUd3fi9jkqnsd3z:btp19bx) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/82a33eea7066c3a1b7fcbdf4e6c68ce32d740eab/README.md#L10)):*
<details><summary><i>Previously, davidsoergel (David Soergel) wrote…</i></summary><blockquote>

A few instances are changed but there are a bunch more...
</blockquote></details>

thanks, fixed the rest.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84)*

**Comment by caisq** [comment]
Still looking. Will comment later.

---

Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[python/tensorflowjs/converters/tf_saved_model_conversion.py, line 164 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9l8W2i2rS4J_pvvrQY:-L9l8W2i2rS4J_pvvrQZ:bc1m9fi) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/bb8b8296bf040ea5e32dac3ec6e410411778860d/python/tensorflowjs/converters/tf_saved_model_conversion.py#L164)):*
> ```
>   print("Tensorflow has deprecated the Session Bundle format, \
>         please migrate to SavedModel.")
> ```

nit: instead of using \, do:

print("Tensorflow has deprecated the Session Bundle format, "
         "please migrate to SavedModel.")

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-:-L9lQ5OL8puj_5n7MzaG:b-j4ktk7)*

**Comment by caisq** [comment]
:lgtm_strong:

---

Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[README.md, line 44 at r4](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9mnQGh7mSIV50gBu6U:-L9mnQGiBHvM6KlM8v7q:bb6tao6) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/19acc2be03519f19a9e58f46f7e61a6e17511bb4/README.md#L44)):*
> ```
> tf_session_bundle_model
> ```

Can we call this `tf_session_bundle` for simplicity and consistency with methods names in TF such as `LoadSessionBundleFromPath`?

---

*[python/tensorflowjs/converters/tf_saved_model_conversion.py, line 146 at r4](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9mnfFX20-09BhSVj9V:-L9mnfFX20-09BhSVj9W:bbo7be4) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/19acc2be03519f19a9e58f46f7e61a6e17511bb4/python/tensorflowjs/converters/tf_saved_model_conversion.py#L146)):*
> ```
> output_dir
> ```

nit: put this on a new line

---

*[python/tensorflowjs/converters/tf_saved_model_conversion_test.py, line 152 at r4](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9mo3zm9xI9Gz8KQan6:-L9mo3zm9xI9Gz8KQan7:b-jxmuqz) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/19acc2be03519f19a9e58f46f7e61a6e17511bb4/python/tensorflowjs/converters/tf_saved_model_conversion_test.py#L152)):*
> ```
> (self._tmp_dir, SESSION_BUNDLE_MODEL_DIR, 'group*-*')
> ```

Should we check the content of these weights files for their correctness?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-:-L9moB8h4SYfjwpQFMRN:b-jbsf8z)*

**Comment by davidsoergel** [comment]
Review status: 0 of 4 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[README.md, line 7 at r4](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9ojaOx8IE4fWWyt4GH:-L9ojaOx8IE4fWWyt4GI:b-kbw0uf) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/19acc2be03519f19a9e58f46f7e61a6e17511bb4/README.md#L7)):*
> ```
> Session Bundle Model
> ```
Mirroring Shanqing's comment below: this can be "SessionBundle" (no need for "Model"), here and throughout.

---

*[README.md, line 44 at r4](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9mnQGh7mSIV50gBu6U:-L9oiz264bA9nBjmtH6b:b32v57) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/19acc2be03519f19a9e58f46f7e61a6e17511bb4/README.md#L44)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> tf_session_bundle_model
> ```

Can we call this `tf_session_bundle` for simplicity and consistency with methods names in TF such as `LoadSessionBundleFromPath`?
</blockquote></details>

+1

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84)*

**Comment by pyu10055** [comment]
Review status: 0 of 4 files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---

*[README.md, line 7 at r4](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9ojaOx8IE4fWWyt4GH:-LA9_ZZG8T2ces8U2NHz:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/19acc2be03519f19a9e58f46f7e61a6e17511bb4/README.md#L7)):*
<details><summary><i>Previously, davidsoergel (David Soergel) wrote…</i></summary><blockquote>

> ```
> Session Bundle Model
> ```
Mirroring Shanqing's comment below: this can be "SessionBundle" (no need for "Model"), here and throughout.
</blockquote></details>

Done.

---

*[README.md, line 44 at r4](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9mnQGh7mSIV50gBu6U:-LA9_dKuB6LuuqZDfpNS:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/19acc2be03519f19a9e58f46f7e61a6e17511bb4/README.md#L44)):*
<details><summary><i>Previously, davidsoergel (David Soergel) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

---

*[python/tensorflowjs/converters/tf_saved_model_conversion.py, line 164 at r3](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9l8W2i2rS4J_pvvrQY:-LA9aY4D5TfIUdYhiZcE:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/bb8b8296bf040ea5e32dac3ec6e410411778860d/python/tensorflowjs/converters/tf_saved_model_conversion.py#L164)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
>   print("Tensorflow has deprecated the Session Bundle format, \
>         please migrate to SavedModel.")
> ```

nit: instead of using \, do:

print("Tensorflow has deprecated the Session Bundle format, "
         "please migrate to SavedModel.")
</blockquote></details>

Done.

---

*[python/tensorflowjs/converters/tf_saved_model_conversion.py, line 146 at r4](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9mnfFX20-09BhSVj9V:-LA9abmyBH5SIfRDePt_:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/19acc2be03519f19a9e58f46f7e61a6e17511bb4/python/tensorflowjs/converters/tf_saved_model_conversion.py#L146)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> output_dir
> ```

nit: put this on a new line
</blockquote></details>

Done.

---

*[python/tensorflowjs/converters/tf_saved_model_conversion_test.py, line 152 at r4](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9mo3zm9xI9Gz8KQan6:-LA9acrl7BgpwFwBFJxO:b-cpk2ft) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/19acc2be03519f19a9e58f46f7e61a6e17511bb4/python/tensorflowjs/converters/tf_saved_model_conversion_test.py#L152)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> (self._tmp_dir, SESSION_BUNDLE_MODEL_DIR, 'group*-*')
> ```

Should we check the content of these weights files for their correctness?
</blockquote></details>

will add the correctness tests in a new PR.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84)*

**Comment by caisq** [comment]
:lgtm_strong:

---

Review status: 0 of 4 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[python/tensorflowjs/converters/tf_saved_model_conversion.py, line 164 at r5](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-LAF9piLA514Xglk5EOl:-LAF9piLA514Xglk5EOm:bcdcqub) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/1190401e9f09c0b0bb8fa17a01de0736bde32c57/python/tensorflowjs/converters/tf_saved_model_conversion.py#L164)):*
> ```
> 
> ```

Remove this comma. String continuation should just work in this case.

---

*[python/tensorflowjs/converters/tf_saved_model_conversion_test.py, line 152 at r4](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-L9mo3zm9xI9Gz8KQan6:-LAFAQi17XE0R7W8O_d3:b951y2z) ([raw file](https://github.com/tensorflow/tfjs-converter/blob/19acc2be03519f19a9e58f46f7e61a6e17511bb4/python/tensorflowjs/converters/tf_saved_model_conversion_test.py#L152)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

will add the correctness tests in a new PR.
</blockquote></details>

Looking forward.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-converter/84#-:-LAFASd2D3u0077khZRE:b-jbsf8z)*

**Pull request merged**
